import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronRight, CircleOff, Info, LoaderCircle } from 'lucide-react';
import type { AuditSessionV2, AuditTensor, CandidateRelation, CaseEvidence, SensitivityResult } from '@/data/auditSessionV2';
import { exactCase, sampleById, type CandidateBundle } from '@/data/auditSessionV2View';
import { KatexSpan } from '@/components/KatexSpan';
import { formalAvailabilityLabel } from './evidencePresentationLogic';

export type FormalStatus = 'supported' | 'not_supported' | 'not_audited' | 'unavailable';
export interface ScopeMapItem { key: string; label: string; bundle: CandidateBundle | null; selected?: boolean; onSelect?: () => void }

export function RelationAuditHeader({ relation, model, localContext, contextCount, local, global, equivalent = false }: { relation: string; model: string; localContext: string; contextCount: string; local: CandidateBundle | null; global: CandidateBundle | null; equivalent?: boolean }) {
  const availability = formalAvailabilityLabel(local, global, equivalent);
  const availabilityValue = availability === 'Formal inference available' ? 'Available' : availability === 'Formal inference unavailable' ? 'Unavailable' : availability.replace(/^Formal inference · /, '');
  return <section className="card border-l-4 border-l-[#16827f] p-5"><h3 className="font-serif text-2xl font-semibold text-[#263b59]">{relation}</h3><div className="mt-4 grid gap-3 text-[12px] text-ink-500 sm:grid-cols-2 lg:grid-cols-4"><HeaderFact label="Model" value={model}/><HeaderFact label="Selected local context" value={localContext}/><HeaderFact label="Contexts" value={contextCount}/><HeaderFact label="Formal inference" value={availabilityValue} available={availability !== 'Not audited' && availability !== 'Formal inference unavailable'}/></div></section>;
}

function HeaderFact({ label, value, available }: { label: string; value: string; available?: boolean }) { return <div><div className="text-[10px] font-semibold uppercase tracking-wider text-ink-400">{label}</div><div className={`mt-1 text-[12px] font-semibold ${available === true ? 'text-[#176e69]' : 'text-ink-700'}`}>{value}</div></div>; }

export function SelectedScopeComparison({ local, global, localLabel, globalLabel, equivalent = false }: { local: CandidateBundle | null; global: CandidateBundle | null; localLabel: string; globalLabel: string; equivalent?: boolean }) {
  return <section className="card overflow-hidden"><header className="border-b border-line px-5 py-4"><div className="eyebrow">Formal audit results</div><h3 className="mt-1 text-[16px] font-semibold text-[#263b59]">Selected Scope Comparison</h3><p className="mt-2 text-[12px] leading-relaxed text-ink-500">{equivalent ? 'Equivalent intervention scope; the frozen records are shown without a strength comparison.' : comparisonText(local, global)}</p><StatusDecisionRule/></header><div className="grid md:grid-cols-2"><ScopeColumn label={localLabel} bundle={local}/><ScopeColumn label={globalLabel} bundle={global} divider/></div></section>;
}

function StatusDecisionRule() {
  return <div className="mt-4 rounded-lg border border-line bg-[#f5f7fa] px-4 py-3"><div className="text-[10px] font-semibold uppercase tracking-wider text-ink-500">How status is assigned</div><div className="mt-2 overflow-x-auto text-[12px] text-ink-700"><KatexSpan tex={'q_i = \\operatorname{BH}(p_1,\\ldots,p_m)_i \\qquad \\mathrm{Supported} \\iff q_i < \\alpha'}/></div><p className="mt-2 text-[11px] leading-relaxed text-ink-500"><b className="text-ink-700">Not supported:</b> qᵢ ≥ α · <b className="text-ink-700">Formal inference unavailable:</b> no valid p or q · <b className="text-ink-700">Not audited:</b> no exact candidate record</p></div>;
}

function ScopeColumn({ label, bundle, divider = false }: { label: string; bundle: CandidateBundle | null; divider?: boolean }) {
  const status = formalStatus(bundle), evidence = bundle?.evidence;
  return <article className={`p-5 ${divider ? 'border-t border-line md:border-l md:border-t-0' : ''}`}><div className="text-[11px] font-semibold uppercase tracking-wider text-accent">{label}</div><div className="mt-4"><StatusBadge status={status}/></div><p className="mt-2 min-h-[36px] text-[12px] leading-relaxed text-ink-500">{statusDescription(status)}</p><dl className="mt-5 space-y-3"><ComparisonMetric label="BH-adjusted q" value={evidence ? displayProbability(evidence.multiplicity.adjusted_q) : '—'} raw={evidence?.multiplicity.adjusted_q}/><ComparisonMetric label="Mean D" value={evidence ? displaySigned(evidence.effect.mean_D) : '—'} raw={evidence?.effect.mean_D}/><ComparisonMetric label="Positive fraction" value={evidence ? displayPercent(evidence.effect.positive_fraction) : '—'} raw={evidence?.effect.positive_fraction}/><ComparisonMetric label="Active / planned" value={evidence ? `${evidence.active_samples.length} / ${evidence.planned_samples.length}` : '—'}/></dl><details className="mt-5 border-t border-line pt-4"><summary className="cursor-pointer text-[11px] font-semibold text-ink-600">Additional statistics</summary><dl className="mt-3 grid gap-3 sm:grid-cols-2"><SmallMetric label="Raw p" value={evidence ? displayProbability(evidence.primary_inference.raw_p) : '—'} raw={evidence?.primary_inference.raw_p}/><SmallMetric label="Median D" value={evidence ? displaySigned(evidence.effect.median_D) : '—'} raw={evidence?.effect.median_D}/><SmallMetric label="Family ID" value={bundle?.family.family_id ?? '—'}/><SmallMetric label="Family size" value={bundle ? String(bundle.family.size) : '—'}/></dl></details></article>;
}

export function MethodSensitivity({ local, global, localLabel, globalLabel }: { local: CandidateBundle | null; global: CandidateBundle | null; localLabel: string; globalLabel: string }) {
  if (!local && !global) return null;
  const columns: Array<[string, CandidateBundle | null]> = [[localLabel, local], [globalLabel, global]];
  return <details className="card min-w-0 p-5"><summary className="cursor-pointer list-none"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="eyebrow">Method & Sensitivity</div><p className="mt-2 break-words text-[12px] text-ink-500">Frozen inference settings and sensitivity results, shown separately for each displayed scope.</p></div><ChevronRight size={17} className="shrink-0 text-ink-400"/></div></summary><div className="mt-5 grid min-w-0 gap-5 border-t border-line pt-5 lg:grid-cols-2">{columns.map(([label, bundle]) => <MethodColumn key={label} label={label} bundle={bundle}/>)}</div></details>;
}

function MethodColumn({ label, bundle }: { label: string; bundle: CandidateBundle | null }) {
  if (!bundle) return <Unavailable text={`${label}: exact candidate not audited.`}/>;
  const inference = bundle.evidence.primary_inference;
  return <article className="min-w-0"><h4 className="text-[13px] font-semibold text-[#263b59]">{label}</h4><div className="mt-3 min-w-0 space-y-3 break-words text-[12px] leading-relaxed text-ink-500"><p><b>Primary inference:</b> {methodLabel(inference.method)}. One-sided candidate-level inference on mean D; settings are frozen offline.</p><p><b>Dependence:</b> {bundle.dependence?.classification?.split('_').join(' ') ?? 'Unavailable'} · <span className="break-all">{bundle.dependence?.inference_engine_selected ?? 'Formal inference unavailable'}</span>.</p><div><b>Sensitivity checks (do not replace primary inference):</b><ul className="mt-2 list-disc space-y-1 pl-5">{bundle.evidence.sensitivity.map(item => <li key={item.name} className="break-all">{sensitivityText(item)}</li>)}</ul></div></div></article>;
}

export function ProvenancePanel({ session, local, global, localLabel, globalLabel }: { session: AuditSessionV2; local: CandidateBundle | null; global: CandidateBundle | null; localLabel: string; globalLabel: string }) {
  const shared = [['Model', String((session.model as any).name)], ['Dataset', String((session.dataset as any).name)], ['Checkpoint hash', String((session.checkpoint as any).sha256 ?? 'Unavailable')], ['Config / protocol hash', String((session.provenance as any).audit_config_sha256 ?? (session.provenance as any).config_sha256 ?? 'Unavailable')]];
  return <details className="card p-5"><summary className="cursor-pointer list-none"><div className="flex items-center justify-between gap-3"><div><div className="eyebrow">Provenance</div><p className="mt-2 text-[12px] text-ink-500">Shared audit provenance and scope-specific frozen hypothesis identities.</p></div><ChevronRight size={17} className="text-ink-400"/></div></summary><div className="mt-5 space-y-6 border-t border-line pt-5"><section><h4 className="text-[13px] font-semibold text-[#263b59]">Shared audit provenance</h4><dl className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{shared.map(([label, value]) => <Provenance key={label} label={label} value={value}/>)}</dl></section><section className="border-t border-line pt-5"><h4 className="text-[13px] font-semibold text-[#263b59]">Hypothesis families</h4><div className="mt-3 grid gap-4 lg:grid-cols-2"><HypothesisProvenance label={localLabel} bundle={local}/><HypothesisProvenance label={globalLabel} bundle={global}/></div></section></div></details>;
}

function HypothesisProvenance({ label, bundle }: { label: string; bundle: CandidateBundle | null }) {
  return <article className="min-w-0 rounded-xl border border-line bg-[#fafbfd] p-4"><h5 className="text-[12px] font-semibold text-accent">{label}</h5>{bundle ? <dl className="mt-3 grid gap-3 sm:grid-cols-2"><Provenance label="Scope" value={bundle.candidate.scope}/><Provenance label="Candidate ID" value={bundle.candidate.candidate_id}/><Provenance label="Family ID" value={bundle.family.family_id}/><Provenance label="Family size" value={String(bundle.family.size)}/></dl> : <p className="mt-3 rounded-lg bg-slate-100 p-3 text-[12px] text-slate-700">Exact candidate not audited</p>}</article>;
}

export function ScopeEvidenceMap({ relation, items, equivalent = false }: { relation: string; items: ScopeMapItem[]; equivalent?: boolean }) {
  return <section className="card overflow-hidden"><header className="border-b border-line px-5 py-4"><div className="eyebrow">Scope Evidence Map</div><h3 className="mt-1 text-[16px] font-semibold text-[#263b59]">{relation}</h3><p className="mt-2 text-[12px] text-ink-500">Frozen candidate-level evidence status across displayed scopes.</p>{equivalent && <p className="mt-2 text-[12px] font-semibold text-sky-800">Equivalent intervention scope: the single retained window and all-retained-window removal represent the same intervention.</p>}</header><div className="overflow-x-auto"><div className="grid min-w-max auto-cols-[220px] grid-flow-col gap-3 p-5">{items.map(item => <ScopeCell key={item.key} item={item}/>)}</div></div></section>;
}

function ScopeCell({ item }: { item: ScopeMapItem }) {
  const status = formalStatus(item.bundle), evidence = item.bundle?.evidence;
  const content = <><div className="flex min-h-[28px] items-start justify-between gap-2"><span className="text-[12px] font-semibold text-[#263b59]">{item.label}</span>{item.selected && <span className="rounded-full bg-[#16827f] px-2 py-0.5 text-[10px] font-semibold text-white">Selected</span>}</div><div className="mt-4"><StatusBadge status={status} compact/></div><dl className="mt-4 space-y-2 text-[12px]"><MapMetric label="q" value={evidence ? displayProbability(evidence.multiplicity.adjusted_q) : '—'} raw={evidence?.multiplicity.adjusted_q}/><MapMetric label="Mean D" value={evidence ? displaySigned(evidence.effect.mean_D) : '—'} raw={evidence?.effect.mean_D}/><MapMetric label="Active / planned" value={evidence ? `${evidence.active_samples.length} / ${evidence.planned_samples.length}` : '—'}/></dl></>;
  const classes = `rounded-xl border p-4 text-left ${item.selected ? 'border-[#16827f] bg-[#edf7f6] ring-1 ring-[#16827f]/20' : 'border-line bg-[#fafbfd]'} ${item.onSelect ? 'transition hover:border-[#16827f]' : ''}`;
  return item.onSelect ? <button type="button" onClick={item.onSelect} className={classes}>{content}</button> : <div className={classes}>{content}</div>;
}

export function EquivalentScopeNotice() { return <p className="rounded-lg border border-sky-200 bg-sky-50 p-4 text-[12px] leading-relaxed text-sky-900">Single-window removal and all-retained-window removal represent the same intervention because there is only one retained window.</p>; }

export function EvidenceDetail({ session, bundle, title, scopeNote }: { session: AuditSessionV2; bundle: CandidateBundle | null; title: string; scopeNote: string }) {
  const [selectedTestId, setSelectedTestId] = useState<number | null>(null);
  useEffect(() => {
    if (!bundle) { setSelectedTestId(null); return; }
    setSelectedTestId(current => current !== null && bundle.evidence.planned_samples.includes(current) ? current : bundle.evidence.planned_samples[0] ?? null);
  }, [bundle?.candidate.candidate_id]);
  if (!bundle) return <Unavailable text="Exact candidate evidence is not audited for this relation and scope."/>;
  const selectedRecord = selectedTestId === null ? null : exactCase(session, bundle.candidate, selectedTestId);
  return <section className="space-y-5"><CandidateAuditHeader title={title} bundle={bundle}/><CaseEvidenceTable session={session} bundle={bundle} selectedTestId={selectedTestId} onSelectTest={setSelectedTestId}/><section aria-live="polite"><div className="mb-3"><div className="eyebrow">Selected Test Detail</div><h3 className="mt-1 text-[16px] font-semibold text-[#263b59]">{selectedTestId === null ? 'No test selected' : `Test ${selectedTestId}`}</h3></div>{selectedRecord ? <CaseCard session={session} candidate={bundle.candidate} record={selectedRecord} scope={scopeNote}/> : <Unavailable text="Unavailable: no exact case matched this planned test, candidate, context, relation, and scope. No fallback was used."/>}</section></section>;
}

function CandidateAuditHeader({ title, bundle }: { title: string; bundle: CandidateBundle }) {
  return <section className="card flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="eyebrow">Candidate-level audit information</div><h3 className="mt-1 font-serif text-xl font-semibold text-[#263b59]">{title}</h3><p className="mt-2 text-[12px] text-ink-500">{bundle.candidate.source_name} → {bundle.candidate.target_name} · {bundle.evidence.active_samples.length} / {bundle.evidence.planned_samples.length} active</p></div><div className="text-right"><StatusBadge status={formalStatus(bundle)}/><p className="mt-2 font-mono text-[11px] text-ink-500" title={rawTitle(bundle.evidence.multiplicity.adjusted_q)}>BH-adjusted q {displayProbability(bundle.evidence.multiplicity.adjusted_q)}</p></div></section>;
}

function CaseEvidenceTable({ session, bundle, selectedTestId, onSelectTest }: { session: AuditSessionV2; bundle: CandidateBundle; selectedTestId: number | null; onSelectTest: (value: number) => void }) {
  const rows = bundle.evidence.planned_samples.map(testId => ({ testId, record: exactCase(session, bundle.candidate, testId) }));
  return <section className="card overflow-hidden"><header className="flex flex-wrap items-end justify-between gap-3 border-b border-line px-5 py-4"><div><div className="eyebrow">All Test Results</div><h3 className="mt-1 text-[16px] font-semibold text-[#263b59]">{rows.length} planned tests</h3></div><p className="text-[11px] text-ink-400">Frozen protocol order · row selection is display-only</p></header><div className="overflow-x-auto"><table className="w-full min-w-[1040px] border-collapse text-left"><thead className="bg-[#f5f7fa] text-[11px] uppercase tracking-wider text-ink-500"><tr>{['Test','Status','D','Focal response','Control mean','Prediction Δ max','Δ MAE','Δ MSE'].map(label => <th key={label} className="whitespace-nowrap border-b border-line px-4 py-3 font-semibold">{label}</th>)}</tr></thead><tbody>{rows.map(({ testId, record }) => <CaseEvidenceRow key={testId} testId={testId} record={record} selected={testId === selectedTestId} onSelect={() => onSelectTest(testId)}/>)}</tbody></table></div></section>;
}

function CaseEvidenceRow({ testId, record, selected, onSelect }: { testId: number; record: CaseEvidence | null; selected: boolean; onSelect: () => void }) {
  const active = record?.status === 'active', metrics = record?.response_metrics as any;
  const status = !record ? 'Unavailable' : active ? 'Active' : 'Inactive';
  const cell = (value: unknown, signed = false) => active ? <span title={rawTitle(value)}>{signed ? displaySigned(value) : displayNumber(value)}</span> : '—';
  return <tr tabIndex={0} role="button" aria-selected={selected} onClick={onSelect} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onSelect(); } }} className={`cursor-pointer border-b border-line text-[12px] outline-none transition last:border-0 hover:bg-[#f5f7fa] focus:bg-[#edf7f6] ${selected ? 'bg-[#edf7f6]' : 'bg-white'}`}><td className="whitespace-nowrap px-4 py-3 font-sans font-semibold tabular-nums text-[#263b59]">{testId}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${status === 'Active' ? 'bg-emerald-50 text-emerald-800' : status === 'Inactive' ? 'bg-amber-50 text-amber-800' : 'bg-slate-100 text-slate-700'}`}>{status}</span></td><td className="px-4 py-3 font-sans tabular-nums text-ink-700">{cell(record?.D, true)}</td><td className="px-4 py-3 font-sans tabular-nums text-ink-700">{cell(record?.focal_response)}</td><td className="px-4 py-3 font-sans tabular-nums text-ink-700">{cell(record?.controls.mean)}</td><td className="px-4 py-3 font-sans tabular-nums text-ink-700">{cell(metrics?.prediction_delta_max)}</td><td className="px-4 py-3 font-sans tabular-nums text-ink-700">{cell(metrics?.error_delta_mae, true)}</td><td className="px-4 py-3 font-sans tabular-nums text-ink-700">{cell(metrics?.error_delta_mse, true)}</td></tr>;
}

function CaseCard({ session, candidate, record, scope }: { session: AuditSessionV2; candidate: CandidateRelation; record: CaseEvidence; scope: string }) {
  const context = record.context as any;
  if (record.status === 'inactive') return <article className="card p-5"><div className="flex items-center gap-2 text-amber-700"><CircleOff size={16}/><h3 className="font-semibold">{candidate.source_name} → {candidate.target_name} · Test {record.sample_id}</h3></div><p className="mt-4 rounded-lg bg-amber-50 p-4 text-[12px] text-amber-900">Not exposed in this sample. No zero value or alternate case was substituted.</p></article>;
  const metrics = record.response_metrics as any, graph = record.graph_effect as any;
  const weight = graph.weight ?? graph.learned_weight ?? graph.learned_edge_weight ?? graph.normalized_weight ?? (Array.isArray(graph.before_weights) ? graph.before_weights[0] : null);
  return <article className="card overflow-hidden"><header className="border-b border-line bg-[#fafbfd] px-5 py-4"><div className="eyebrow">{scope}</div><h3 className="mt-1 font-serif text-xl font-semibold text-[#263b59]">{candidate.source_name} → {candidate.target_name} · Test {record.sample_id}</h3>{typeof context.current_period === 'number' && <p className="mt-1 text-[11px] text-ink-400">Scale index {candidate.scale_index} · current FFT period {context.current_period} (case metadata)</p>}</header><div className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Learned edge weight" value={displayNumber(weight)} raw={weight}/><Metric label="Structural rank" value={displayNullable(graph.rank ?? record.rank)}/><Metric label="Focal response" value={displayNumber(record.focal_response)} raw={record.focal_response}/><Metric label="Unique controls" value={String(record.controls.unique_count)}/><Metric label="Control mean" value={displayNumber(record.controls.mean)} raw={record.controls.mean}/><Metric label="Control median" value={displayNumber(record.controls.median)} raw={record.controls.median}/><Metric label="D" value={displaySigned(record.D)} raw={record.D}/><Metric label="Percentile" value={record.percentile === null ? 'Unavailable' : `${record.percentile.toFixed(2)}%`} raw={record.percentile}/><Metric label="Prediction Δ max" value={displayNumber(metrics.prediction_delta_max)} raw={metrics.prediction_delta_max}/><Metric label="Δ MAE" value={displaySigned(metrics.error_delta_mae)} raw={metrics.error_delta_mae}/><Metric label="Δ MSE" value={displaySigned(metrics.error_delta_mse)} raw={metrics.error_delta_mse}/></div><div className="border-t border-line p-5"><TrajectoryPanel session={session} target={candidate.target} records={[["Relation Removed", record]]} sampleId={record.sample_id} compact/></div></article>;
}

function TrajectoryPanel({ session, target, records, sampleId, compact = false }: { session: AuditSessionV2; target: number; records: Array<[string, CaseEvidence | null]>; sampleId: number | null; compact?: boolean }) {
  const sample = sampleId === null ? null : sampleById(session, sampleId);
  if (!sample) return <Unavailable text="Trajectory unavailable: exact audit sample was not found."/>;
  const series: Array<[string, number[] | null]> = [['Ground Truth', tensorSeries(sample.ground_truth, target)], ['Original Prediction', tensorSeries(sample.baseline_prediction, target)], ...records.map(([label, record]) => [label, interventionSeries(record, target)] as [string, number[] | null])];
  if (series.some(([, values]) => !values)) return <Unavailable text="Unavailable: the selected same-test trajectory set is incomplete. No fallback was synthesized."/>;
  const length = Math.min(...series.map(([, values]) => values!.length)), all = series.flatMap(([, values]) => values!.slice(0, length));
  const min = Math.min(...all), max = Math.max(...all), range = max - min || 1, colors = ['#6b7280','#263b59','#d97706','#16827f'];
  const points = (values: number[]) => values.slice(0, length).map((value, index) => `${(index / Math.max(1, length - 1)) * 100},${94 - ((value - min) / range) * 88}`).join(' ');
  return <div><div className="flex flex-wrap items-center justify-between gap-2"><div className="eyebrow">Prediction comparison · Test {sampleId}</div><div className="flex flex-wrap gap-3">{series.map(([name], index) => <span key={name} className="flex items-center gap-1 text-[11px] text-ink-500"><i className="h-0.5 w-4" style={{ background: colors[index] }}/>{name}</span>)}</div></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" className={`mt-3 w-full rounded-lg border border-line bg-white ${compact ? 'h-44' : 'h-64'}`} role="img" aria-label={`Same-test trajectory comparison for test ${sampleId}`}>{series.map(([name, values], index) => <polyline key={name} fill="none" stroke={colors[index]} strokeWidth={index < 2 ? 1 : 1.25} vectorEffect="non-scaling-stroke" points={points(values!)}/>)}</svg></div>;
}

function formalStatus(bundle: CandidateBundle | null): FormalStatus { if (!bundle) return 'not_audited'; if (bundle.evidence.primary_inference.status !== 'complete' || bundle.evidence.multiplicity.supported === null) return 'unavailable'; return bundle.evidence.multiplicity.supported ? 'supported' : 'not_supported'; }
function StatusBadge({ status, compact = false }: { status: FormalStatus; compact?: boolean }) { const p = statusPresentation(status); return <span className={`inline-flex items-center gap-1.5 rounded-full font-semibold ${compact ? 'px-2.5 py-1 text-[11px]' : 'px-3 py-1.5 text-[12px]'} ${p.className}`}>{p.icon}{p.label}</span>; }
function statusPresentation(status: FormalStatus) { if (status === 'supported') return { label: 'Supported', className: 'bg-emerald-50 text-emerald-800', icon: <CheckCircle2 size={13}/> }; if (status === 'not_supported') return { label: 'Not supported', className: 'bg-amber-50 text-amber-800', icon: <Info size={13}/> }; if (status === 'unavailable') return { label: 'Formal inference unavailable', className: 'bg-slate-100 text-slate-700', icon: <CircleOff size={13}/> }; return { label: 'Not audited', className: 'bg-gray-100 text-gray-700', icon: <CircleOff size={13}/> }; }
function statusDescription(status: FormalStatus) { if (status === 'supported') return 'Statistically supported after BH correction.'; if (status === 'not_supported') return 'No consistent functional evidence was established under this audited hypothesis.'; if (status === 'unavailable') return 'A candidate record exists, but formal inference is unavailable.'; return 'No exact candidate exists for this relation and scope.'; }
function comparisonText(local: CandidateBundle | null, global: CandidateBundle | null) { const l = formalStatus(local), g = formalStatus(global); if (l === 'supported' && g === 'supported') return 'Supported in both audited scopes.'; if (l === 'not_supported' && g === 'not_supported') return 'Not supported in either audited scope. No consistent functional evidence was established under either audited hypothesis.'; if ((l === 'supported' && g === 'not_supported') || (l === 'not_supported' && g === 'supported')) return 'Support status differs between the two audited scopes.'; if (l === 'not_audited' || g === 'not_audited') return 'An exact candidate is not audited for one or both displayed scopes.'; return 'Formal inference is unavailable for one or both displayed scopes.'; }

function ComparisonMetric({ label, value, raw }: { label: string; value: string; raw?: unknown }) { return <div className="flex items-baseline justify-between gap-4 border-b border-line pb-2 last:border-0"><dt className="text-[12px] text-ink-500">{label}</dt><dd className="font-mono text-[14px] font-semibold text-ink-800" title={rawTitle(raw)}>{value}</dd></div>; }
function SmallMetric({ label, value, raw }: { label: string; value: string; raw?: unknown }) { return <div className="rounded-lg bg-[#f5f7fa] p-3"><dt className="text-[10px] uppercase tracking-wider text-ink-400">{label}</dt><dd className="mt-1 break-all font-mono text-[12px] text-ink-700" title={rawTitle(raw)}>{value}</dd></div>; }
function MapMetric({ label, value, raw }: { label: string; value: string; raw?: unknown }) { return <div className="flex items-baseline justify-between gap-3"><dt className="text-ink-400">{label}</dt><dd className="font-mono font-semibold text-ink-700" title={rawTitle(raw)}>{value}</dd></div>; }
function Metric({ label, value, raw }: { label: string; value: string; raw?: unknown }) { return <div className="rounded-lg bg-[#f5f7fa] p-3" title={rawTitle(raw)}><div className="text-[10px] uppercase tracking-wider text-ink-400">{label}</div><div className="mt-1 break-words font-mono text-[13px] font-semibold text-ink-800">{value}</div></div>; }
function Provenance({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-[#f5f7fa] p-3"><dt className="text-[10px] uppercase tracking-wider text-ink-400">{label}</dt><dd className="mt-1 break-all font-mono text-[11px] text-ink-700" title={value}>{value}</dd></div>; }
export function Loading({ label }: { label: string }) { return <div className="mx-auto flex max-w-[1400px] items-center justify-center px-5 py-14 text-[12px] text-ink-400"><LoaderCircle className="mr-2 animate-spin" size={17}/>{label}</div>; }
export function LoadFailure({ error }: { error: string }) { return <div className="mx-auto max-w-[1400px] px-5 py-8"><div className="rounded-xl border border-red-200 bg-red-50 p-5 text-[12px] text-red-900"><AlertTriangle size={16}/><b className="ml-2">Formal evidence could not be validated.</b><p className="mt-2">{error}</p></div></div>; }
export function Unavailable({ text }: { text: string }) { return <div className="rounded-xl border border-slate-200 bg-slate-50 p-5 text-[12px] text-slate-800"><CircleOff className="mr-2 inline" size={14}/>{text}</div>; }

function methodLabel(value: string | null) { if (!value) return 'Formal inference unavailable'; if (value.includes('moving_block')) return 'Dependence-aware moving-block inference'; if (value.includes('exact_sign_flip')) return 'One-sided complete exact sign-flip'; return value.split('_').join(' '); }
function sensitivityText(item: SensitivityResult) { const fact = item.p !== undefined ? `p=${displayProbability(item.p)}` : item.q !== undefined ? `q=${displayProbability(item.q)}` : item.CI !== undefined ? `CI=${JSON.stringify(item.CI)}` : item.value !== undefined ? JSON.stringify(item.value) : displayNullable(item.statistic); return `${item.name.split('_').join(' ')}: ${fact}`; }
function tensorSeries(tensor: AuditTensor, target: number): number[] | null { const values = tensor?.values as unknown; if (!Array.isArray(values)) return null; const output = values.map(row => Array.isArray(row) ? row[target] : null); return output.every(value => typeof value === 'number' && Number.isFinite(value)) ? output as number[] : null; }
function interventionSeries(record: CaseEvidence | null, target: number): number[] | null { if (!record || record.status !== 'active') return null; const ref = record.intervention_output_reference as any, tensor = ref?.value?.values ? ref.value : ref?.values ? ref : null; return tensor ? tensorSeries(tensor, target) : null; }
function rawTitle(value: unknown) { return typeof value === 'number' && Number.isFinite(value) ? String(value) : undefined; }
function displayNumber(value: unknown) { if (typeof value !== 'number' || !Number.isFinite(value)) return '—'; const m = Math.abs(value); return m !== 0 && (m < .001 || m >= 1000) ? value.toExponential(2) : value.toLocaleString('en-US', { maximumSignificantDigits: 4 }); }
function displaySigned(value: unknown) { if (typeof value !== 'number' || !Number.isFinite(value)) return '—'; return `${value > 0 ? '+' : ''}${displayNumber(value)}`; }
function displayProbability(value: unknown) { if (typeof value !== 'number' || !Number.isFinite(value)) return '—'; return value !== 0 && value < .001 ? value.toExponential(1) : value.toLocaleString('en-US', { maximumSignificantDigits: 3 }); }
function displayPercent(value: unknown) { return typeof value === 'number' && Number.isFinite(value) ? `${(value * 100).toFixed(1)}%` : '—'; }
function displayNullable(value: unknown) { return value === null || value === undefined ? '—' : String(value); }
