import { useRef } from 'react';
import { Database, FileJson, LoaderCircle, RotateCcw, ShieldCheck, Upload, X } from 'lucide-react';
import { useAuditSessionStore } from '@/store/useAuditSessionStore';
import { useWorkflowStore } from '@/store/useWorkflowStore';

export function AuditSessionImport() {
  const inputRef = useRef<HTMLInputElement>(null);
  const model = useWorkflowStore(state => state.model);
  const setModel = useWorkflowStore(state => state.setModel);
  const source = useAuditSessionStore(state => state.source);
  const session = useAuditSessionStore(state => state.session);
  const sessionV2 = useAuditSessionStore(state => state.sessionV2);
  const fileName = useAuditSessionStore(state => state.fileName);
  const previousModel = useAuditSessionStore(state => state.previousModel);
  const importState = useAuditSessionStore(state => state.importState);
  const errors = useAuditSessionStore(state => state.errors);
  const importFile = useAuditSessionStore(state => state.importFile);
  const closeSession = useAuditSessionStore(state => state.closeSession);
  const clearError = useAuditSessionStore(state => state.clearError);

  const chooseFile = async (file: File | undefined) => {
    if (!file) return;
    const imported = await importFile(file, model);
    if (imported) {
      setModel(String(imported.model.name));
      setTimeout(() => document.getElementById('discovery-workspace')?.scrollIntoView({ behavior: 'smooth' }), 0);
    }
    if (inputRef.current) inputRef.current.value = '';
  };
  const restoreDemo = () => {
    const restoreModel = previousModel ?? 'DGraFormer';
    closeSession();
    setModel(restoreModel);
  };
  const busy = importState === 'reading' || importState === 'validating';

  return <section id="audit-session-source" className="border-b border-line bg-[#f5f7fa]">
    <div className="mx-auto max-w-[1400px] px-5 py-8">
      <div className="mb-4 flex flex-wrap items-end justify-between gap-3">
        <div><div className="eyebrow">Data source</div><h2 className="mt-1 font-serif text-[27px] font-semibold">Built-in Demo or Portable Audit Session</h2></div>
        <div className="rounded-full border border-line bg-white px-3 py-1.5 text-[10px] font-semibold text-ink-600">
          {source === 'imported' ? 'Imported Audit Session' : 'Built-in Demo'}
        </div>
      </div>
      <div className="grid gap-4 lg:grid-cols-2">
        <article className={`rounded-xl border p-5 ${source === 'built_in' ? 'border-accent/40 bg-white shadow-card' : 'border-line bg-white/60'}`}>
          <div className="flex items-center gap-2 text-[#263b59]"><Database size={17}/><h3 className="text-[15px] font-semibold">Explore Built-in Demo</h3></div>
          <p className="mt-3 text-[11px] leading-relaxed text-ink-500">Use the bundled DGraFormer and MSGNet ETTh1 evidence catalogs. These remain available locally and are restored when an imported session is closed.</p>
          {source === 'imported' && <button onClick={restoreDemo} className="mt-4 inline-flex items-center gap-2 rounded-lg border border-[#263b59] bg-white px-4 py-2 text-[11px] font-semibold text-[#263b59]"><RotateCcw size={14}/>Return to Built-in Demo</button>}
        </article>
        <article className={`rounded-xl border p-5 ${source === 'imported' ? 'border-[#16827f] bg-[#edf7f6]' : 'border-line bg-white'}`}>
          <div className="flex items-center gap-2 text-[#176e69]"><FileJson size={17}/><h3 className="text-[15px] font-semibold">Import Audit Session</h3></div>
          <p className="mt-3 text-[11px] leading-relaxed text-ink-500">Load an audit session generated by the DGraInsight offline pipeline. Model execution and intervention analysis are performed offline.</p>
          <input ref={inputRef} type="file" accept="application/json,.json" className="hidden" onChange={event => void chooseFile(event.target.files?.[0])}/>
          <button disabled={busy} onClick={() => inputRef.current?.click()} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[#263b59] px-4 py-2 text-[11px] font-semibold text-white disabled:opacity-60">
            {busy ? <LoaderCircle size={14} className="animate-spin"/> : <Upload size={14}/>}
            {busy ? (importState === 'reading' ? 'Reading file…' : 'Validating session…') : 'Choose DGraInsight Session'}
          </button>
          <p className="mt-2 text-[9px] text-ink-400">Validated Session v2 and legacy Session v1 files are accepted. Corrupted or incompatible evidence is rejected atomically.</p>
        </article>
      </div>

      {(session || sessionV2) && <div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div><div className="flex items-center gap-2 text-[11px] font-semibold text-emerald-800"><ShieldCheck size={15}/>Validated imported source</div><p className="mt-1 text-[10px] text-emerald-700">{fileName}</p></div>
          <button onClick={restoreDemo} className="inline-flex items-center gap-1 text-[10px] font-semibold text-emerald-800"><X size={13}/>Close Imported Session</button>
        </div>
        <dl className="mt-4 grid gap-3 text-[10px] sm:grid-cols-2 lg:grid-cols-5">
          <SourceField label="Version" value={sessionV2 ? 'Session v2' : 'Legacy Session v1'}/><SourceField label="Model" value={(sessionV2 ?? session!).model.name as string}/><SourceField label="Dataset" value={(sessionV2 ?? session!).dataset.name as string}/><SourceField label="Adapter" value={(sessionV2 ?? session!).model.adapter as string}/><SourceField label="Checkpoint" value={`${String((sessionV2 ?? session!).checkpoint.sha256).slice(0, 16)}…`}/>
        </dl>
      </div>}

      {errors.length > 0 && <div role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-red-900">
        <div className="flex items-start justify-between gap-3"><div><h3 className="text-[13px] font-semibold">Invalid or incompatible DGraInsight Audit Session</h3><p className="mt-1 text-[10px] text-red-700">The active data source was not changed.</p></div><button onClick={clearError} aria-label="Dismiss import errors"><X size={15}/></button></div>
        <ul className="mt-3 list-disc space-y-1 pl-5 text-[10px] leading-relaxed">{errors.slice(0, 8).map((error, index) => <li key={`${index}-${error}`}>{error}</li>)}</ul>
        {errors.length > 8 && <p className="mt-2 text-[9px] text-red-700">{errors.length - 8} additional validation errors were suppressed.</p>}
      </div>}
    </div>
  </section>;
}

function SourceField({ label, value }: { label: string; value: string }) {
  return <div className="rounded-lg bg-white/70 p-3"><dt className="uppercase tracking-wider text-emerald-700">{label}</dt><dd className="mt-1 break-all font-mono font-semibold text-emerald-950">{value}</dd></div>;
}
