import { useEffect, useState } from 'react';
import { Section } from './layout/Section';

type Metrics = { prediction_delta_abs:number; error_delta_mae:number; control_mean_prediction_delta_abs:number; bh_adjusted_p:number };
type Case = { id:string; sample:number; edge:[number,number]; retained_windows:number[]; exposed_windows:number[]; affected_exposed_windows:number[]; metrics:Metrics; baseline_prediction:number[][]; intervention_prediction:number[][]; ground_truth:number[][]; variable_ranking:{variable:string;mean_absolute_prediction_delta:number}[] };
type Catalog = { dataset:string; samples:number[]; edges:[number,number][]; variables:string[]; cases:Case[]; notice:string; cross_run:{status:string;metrics:null} };
const names=['HUFL','HULL','MUFL','MULL','LUFL','LULL','OT'];
const dataUrl=(dataset:string)=>`${import.meta.env.BASE_URL}data/evidence/${dataset.toLowerCase()}_global_intervention_catalog.json`;

export function GlobalInterventionJourney({dataset='ETTh1'}:{dataset?:string}) {
  const [catalog,setCatalog]=useState<Catalog|null>(null),[sample,setSample]=useState(0),[edge,setEdge]=useState(''),[variable,setVariable]=useState(0),[error,setError]=useState(false);
  useEffect(()=>{setCatalog(null);setError(false);fetch(dataUrl(dataset)).then(r=>{if(!r.ok)throw Error();return r.json()}).then((next:Catalog)=>{setCatalog(next);setSample(next.samples[0]);setEdge(next.edges[0].join('->'));setVariable(0)}).catch(()=>setError(true))},[dataset]);
  const current=catalog?.cases.find(c=>c.sample===sample&&c.edge.join('->')===edge),rows=catalog?.cases.filter(c=>c.edge.join('->')===edge)??[];
  return <Section id="global-intervention-lab" eyebrow={`Precomputed global-edge intervention · ${dataset}`} title="Remove one relation everywhere it is retained" intro="The selected directed edge is removed and its source row renormalized in every final-schedule graph window where that edge has positive normalized weight." className="bg-[#f5f8fb]">
    {error&&<div className="card border-red-200 p-5 text-sm text-red-700">Global intervention catalog unavailable. No substitute result was generated.</div>}
    {!catalog&&!error&&<div className="card p-5 text-sm text-ink-400">Loading audited {dataset} global-edge evidence…</div>}
    {catalog&&current&&<div className="space-y-5">
      <div className="card grid gap-4 p-5 md:grid-cols-3"><Choice label="Test sample" value={String(sample)} change={v=>setSample(+v)} options={catalog.samples.map(x=>[String(x),`${catalog.dataset} · test ${x}`])}/><Choice label="Global candidate edge" value={edge} change={setEdge} options={catalog.edges.map(e=>[e.join('->'),`${names[e[0]]} → ${names[e[1]]}`])}/><Choice label="Output variable" value={String(variable)} change={v=>setVariable(+v)} options={catalog.variables.map((x,i)=>[String(i),x])}/></div>
      <Summary rows={rows} selected={sample} select={setSample}/>
      <div className="card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-semibold uppercase tracking-wider text-accent">Global structural intervention</div><h3 className="mt-1 font-serif text-2xl font-semibold text-[#263b59]">{names[current.edge[0]]} → {names[current.edge[1]]} · test {current.sample}</h3></div><span className="rounded-full bg-[#edf6f5] px-3 py-1 text-[11px] font-semibold text-[#176e69]">{current.affected_exposed_windows.length?`${current.affected_exposed_windows.length} exposed window(s) affected`:'Not exposed'}</span></div>
        <div className="mt-4 grid gap-3 sm:grid-cols-3"><Mini label="Retained windows" value={current.retained_windows.join(', ')}/><Mini label="Test input windows" value={current.exposed_windows.join(', ')}/><Mini label="Affected intersection" value={current.affected_exposed_windows.join(', ')||'none'}/></div>
        {!current.affected_exposed_windows.length?<p className="mt-5 rounded-lg bg-amber-50 p-4 text-sm text-amber-800">Not exposed: this test input did not use any window retaining the selected edge. Response and control values are not interpreted.</p>:<><div className="mt-6 space-y-5"><ChartBlock title={`Prediction trajectory · ${catalog.variables[variable]}`} base={current.baseline_prediction.map(x=>x[variable])} removed={current.intervention_prediction.map(x=>x[variable])}/><ChartBlock title={`Absolute error trajectory · ${catalog.variables[variable]}`} base={current.baseline_prediction.map((x,i)=>Math.abs(x[variable]-current.ground_truth[i][variable]))} removed={current.intervention_prediction.map((x,i)=>Math.abs(x[variable]-current.ground_truth[i][variable]))}/></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Mini label="Prediction Δ" value={fmt(current.metrics.prediction_delta_abs)}/><Mini label="MAE Δ" value={signed(current.metrics.error_delta_mae)}/><Mini label="Matched-control mean" value={fmt(current.metrics.control_mean_prediction_delta_abs)}/><Mini label="BH adjusted p" value={current.metrics.bh_adjusted_p.toFixed(3)}/></div><p className="mt-4 text-[11px] text-ink-500">Largest mean output response: {current.variable_ranking[0].variable} ({fmt(current.variable_ranking[0].mean_absolute_prediction_delta)}). This is model-internal intervention evidence, not a real-world causal claim.</p></>}
      </div><div className="rounded-lg border border-[#d6e3ec] bg-white px-4 py-3 text-[11px] text-ink-500">{catalog.notice} Cross-run evidence remains {catalog.cross_run.status} / null.</div>
    </div>}
  </Section>
}

function Summary({rows,selected,select}:{rows:Case[];selected:number;select:(x:number)=>void}){const exposed=rows.filter(x=>x.affected_exposed_windows.length),up=exposed.filter(x=>x.metrics.error_delta_mae>0).length,down=exposed.filter(x=>x.metrics.error_delta_mae<0).length,unchanged=exposed.length-up-down;return <div className="card p-5"><h3 className="font-serif text-xl font-semibold text-[#263b59]">Global response across audited tests</h3><p className="mt-1 text-[11px] text-ink-400">{exposed.length}/{rows.length} exposed · MAE increased/decreased/unchanged {up}/{down}/{unchanged} · no BH-supported cases</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-[11px]"><thead className="text-ink-400"><tr><th className="p-2">Test</th><th>Affected windows</th><th>Prediction Δ</th><th>MAE Δ</th><th>Top output</th></tr></thead><tbody>{rows.map(c=><tr key={c.id} onClick={()=>select(c.sample)} className={`cursor-pointer border-t border-line ${selected===c.sample?'bg-[#edf6f5]':''}`}><td className="p-2 font-semibold">test {c.sample}</td>{!c.affected_exposed_windows.length?<td colSpan={4} className="font-semibold text-amber-700">Not exposed</td>:<><td>{c.affected_exposed_windows.join(', ')}</td><td>{fmt(c.metrics.prediction_delta_abs)}</td><td>{signed(c.metrics.error_delta_mae)}</td><td>{c.variable_ranking[0].variable}</td></>}</tr>)}</tbody></table></div></div>}
function Choice({label,value,change,options}:{label:string;value:string;change:(v:string)=>void;options:string[][]}){return <label><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wider text-ink-400">{label}</span><select className="w-full rounded-lg border border-[#cad4df] bg-white px-3 py-2.5 text-[13px] font-semibold" value={value} onChange={e=>change(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-[#f5f7fa] p-3"><div className="text-[9.5px] uppercase tracking-wider text-ink-400">{label}</div><div className="mt-1 text-[13px] font-semibold text-ink-800">{value}</div></div>}
function ChartBlock({title,base,removed}:{title:string;base:number[];removed:number[]}){return <div><div className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-ink-400">{title}</div><Trajectory base={base} removed={removed}/></div>}
function Trajectory({base,removed}:{base:number[];removed:number[]}){const vals=[...base,...removed],min=Math.min(...vals),max=Math.max(...vals),span=Math.max(max-min,1e-9),path=(a:number[])=>a.map((v,i)=>`${i?'L':'M'} ${55+i/95*920} ${245-(v-min)/span*205}`).join(' ');return <div className="overflow-x-auto rounded-lg border border-line bg-white"><svg viewBox="0 0 1000 285" className="min-w-[650px]"><line x1="55" y1="245" x2="975" y2="245" stroke="#cbd5df"/><path d={path(base)} fill="none" stroke="#16827f" strokeWidth="2.2"/><path d={path(removed)} fill="none" stroke="#d65b52" strokeWidth="2.2"/><text x="60" y="22" fontSize="11" fill="#16827f">Baseline</text><text x="135" y="22" fontSize="11" fill="#d65b52">Global edge removed</text></svg></div>}
const fmt=(x:number)=>x.toFixed(6),signed=(x:number)=>`${x>=0?'+':''}${x.toFixed(6)}`;
