import { useEffect, useState, type ReactNode } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowDown, CheckCircle2, CircleDashed, Pause, Play, RotateCcw } from 'lucide-react';
import { Section } from './layout/Section';
import { CrossSampleProfile } from './CrossSampleProfile';

interface EdgeOption { edge_id:string;source:number;target:number;source_name:string;target_name:string;windows:number[];topk_score:number;normalized_weight:number;retained_edge_rank:number }
interface Metrics { baseline_mae:number;intervention_mae:number;prediction_delta_abs:number;prediction_delta_rel:number;error_delta_mae:number;control_mean_prediction_delta_abs:number;control_percentile:number;empirical_p:number;bh_adjusted_p:number;standardized_effect_size:number|null;effect_difference_bootstrap_ci:[number,number] }
interface VariableDiagnostic { variable:string;mean_absolute_prediction_delta:number;max_absolute_prediction_delta:number;peak_step:number;mean_absolute_error_delta:number }
interface ResponseInterval { start_step:number;end_step:number;peak_step:number;peak_impact:number;share_of_total_impact:number }
interface CaseRecord { conclusion_id:string;sample_index:number;window:number;window_active:boolean;window_exposure_count:number;active_windows:number[];edge:EdgeOption;structural_metrics:Metrics;structural_metric_status:{standardized_effect_size:{status:string;reason:string|null}};step_impact:number[];baseline_prediction:number[][];intervention_prediction:number[][];ground_truth:number[][];diagnostic_localization:{response_interval_rule:string;response_threshold:number|null;variable_ranking:VariableDiagnostic[];response_intervals:ResponseInterval[]};controls:{repetitions:number;random_seed:number} }
interface Catalog { dataset:string;samples:number[];variables:string[];edges:EdgeOption[];cases:CaseRecord[];notice:string }

const dataUrl=(dataset:string)=>`${import.meta.env.BASE_URL}data/evidence/${dataset.toLowerCase()}_intervention_catalog.json`;
const STAGES=['Candidate selected','Structural intervention','Forecast trajectory','Error & localization','Matched controls','Diagnostic summary'];
const DEFAULT_SAMPLE=1611, DEFAULT_EDGE='0->4', DEFAULT_WINDOW=0;

export function InterventionJourney({dataset='ETTh1'}:{dataset?:string}){
  const [catalog,setCatalog]=useState<Catalog|null>(null),[error,setError]=useState(false);
  const [sample,setSample]=useState(0),[edgeId,setEdgeId]=useState(''),[windowId,setWindowId]=useState(0),[variableIndex,setVariableIndex]=useState(4);
  const [revealed,setRevealed]=useState(1),[playing,setPlaying]=useState(true);
  useEffect(()=>{setCatalog(null);setError(false);fetch(dataUrl(dataset)).then(r=>{if(!r.ok)throw new Error();return r.json()}).then((d:Catalog)=>{const preferredEdge=d.edges.find(e=>e.edge_id===DEFAULT_EDGE)??d.edges[0];setCatalog(d);setSample(d.samples.includes(DEFAULT_SAMPLE)?DEFAULT_SAMPLE:d.samples[0]);setEdgeId(preferredEdge.edge_id);setWindowId(preferredEdge.windows.includes(DEFAULT_WINDOW)?DEFAULT_WINDOW:preferredEdge.windows[0])}).catch(()=>setError(true))},[dataset]);
  const edge=catalog?.edges.find(e=>e.edge_id===edgeId);
  const current=catalog?.cases.find(c=>c.sample_index===sample&&c.window===windowId&&`${c.edge.source}->${c.edge.target}`===edgeId);
  useEffect(()=>{setRevealed(1);setPlaying(true)},[sample,edgeId,windowId]);
  useEffect(()=>{if(current)setVariableIndex(current.edge.target)},[current?.conclusion_id]);
  useEffect(()=>{if(!playing||revealed>=STAGES.length)return;const timer=window.setTimeout(()=>setRevealed(v=>v+1),1050);return()=>window.clearTimeout(timer)},[playing,revealed]);
  useEffect(()=>{if(revealed>=STAGES.length)setPlaying(false)},[revealed]);
  const chooseEdge=(id:string)=>{setEdgeId(id);const next=catalog?.edges.find(e=>e.edge_id===id);if(next)setWindowId(next.windows[0])};
  return <Section id="intervention-lab" eyebrow={`Precomputed intervention lab · ${dataset}`} title="Watch a candidate-edge removal unfold" intro="Choose an audited sample, candidate edge and retained graph window. Every trajectory and diagnostic below is derived from stored checkpoint outputs and real test targets." className="bg-[#f5f8fb]">
    {error&&<div className="card border-red-200 p-5 text-sm text-red-700">Audited intervention catalog unavailable. No substitute result was generated.</div>}
    {!catalog&&!error&&<div className="card p-5 text-sm text-ink-400">Loading the audited {dataset} catalog…</div>}
    {catalog&&current&&edge&&<div className="space-y-5">
      <div className="card grid gap-4 p-5 md:grid-cols-3"><Choice label="Test sample" value={String(sample)} onChange={v=>setSample(Number(v))} options={catalog.samples.map(v=>({value:String(v),label:`${catalog.dataset} · test ${v}`}))}/><Choice label="Candidate edge" value={edgeId} onChange={chooseEdge} options={catalog.edges.map(e=>({value:e.edge_id,label:`${e.source_name} → ${e.target_name}`}))}/><Choice label="Retained graph window" value={String(windowId)} onChange={v=>setWindowId(Number(v))} options={edge.windows.map(v=>({value:String(v),label:`Window ${v}`}))}/><div className="md:col-span-3 flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4"><div className="flex flex-wrap gap-2"><Tag text={`Real ${catalog.dataset} checkpoint`}/><Tag text="Final schedule · 0.1 static + 0.9 learned"/><Tag text="Stored evidence only"/></div><div className="flex gap-2"><button className="journey-button" onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={13}/>:<Play size={13}/>} {playing?'Pause':'Continue'}</button><button className="journey-button" onClick={()=>{setRevealed(1);setPlaying(true)}}><RotateCcw size={13}/>Replay</button></div></div></div>
      <CrossSampleProfile cases={catalog.cases.filter(c=>c.window===windowId&&`${c.edge.source}->${c.edge.target}`===edgeId)} selectedSample={sample} onSelect={setSample}/>
      {current.window_active===false?<UnexposedCase record={current}/>:<div>
      <div className="grid gap-4 lg:grid-cols-[210px_1fr]"><ol className="card h-fit p-3">{STAGES.map((s,i)=><li key={s} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-[12px] ${i<revealed?'bg-[#edf6f5] font-semibold text-[#176e69]':'text-ink-300'}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full text-[10px] ${i<revealed?'bg-[#16827f] text-white':'bg-[#edf0f3]'}`}>{i+1}</span>{s}</li>)}</ol>
        <div className="space-y-3"><AnimatePresence initial={false}>
          {revealed>=1&&<Stage key="s1" index={1} title="A structural candidate is selected"><div className="flex justify-between gap-4"><div><div className="font-serif text-[27px] font-semibold text-[#263b59]">{edge.source_name} <span className="text-accent">→</span> {edge.target_name}</div><p className="mt-2 text-[12px] text-ink-500">Sample {sample} · window {windowId} · retained-edge rank {current.edge.retained_edge_rank} · Top-K score {fmt(current.edge.topk_score)}</p></div><Tag text="Candidate Pattern"/></div></Stage>}
          {revealed>=2&&<Connector key="c1"/>}{revealed>=2&&<Stage key="s2" index={2} title="The selected edge is removed and its row renormalized"><div className="grid gap-3 sm:grid-cols-3"><Mini label="Before" value={fmt(current.edge.normalized_weight)} note="normalized channel weight"/><Mini label="After" value="0.000000" note="selected structural edge"/><Mini label="Protocol" value="Renormalized" note="checkpoint parameters frozen"/></div></Stage>}
          {revealed>=3&&<Connector key="c2"/>}{revealed>=3&&<Stage key="s3" index={3} title="Forecast trajectory: truth, baseline and edge removed"><div className="mb-3 max-w-xs"><Choice label="Output variable" value={String(variableIndex)} onChange={v=>setVariableIndex(Number(v))} options={catalog.variables.map((v,i)=>({value:String(i),label:v}))}/></div><ForecastChart record={current} variableIndex={variableIndex}/><div className="mt-4 grid gap-3 sm:grid-cols-3"><Mini label="Mean absolute prediction Δ" value={fmt(current.structural_metrics.prediction_delta_abs)} note="96 steps × 7 variables"/><Mini label="Relative prediction Δ" value={fmt(current.structural_metrics.prediction_delta_rel)}/><Mini label="Largest step response" value={fmt(Math.max(...current.step_impact))} note={`forecast step ${current.step_impact.indexOf(Math.max(...current.step_impact))+1}`}/></div></Stage>}
          {revealed>=4&&<Connector key="c3"/>}{revealed>=4&&<Stage key="s4" index={4} title="Error trajectory and measured response localization"><ErrorChart record={current} variableIndex={variableIndex}/><DiagnosticLocalization record={current}/><div className="mt-4 grid gap-3 sm:grid-cols-3"><Mini label="Baseline MAE" value={fmt(current.structural_metrics.baseline_mae)}/><Mini label="Intervention MAE" value={fmt(current.structural_metrics.intervention_mae)}/><Mini label="MAE Δ" value={signed(current.structural_metrics.error_delta_mae)} note={performanceLabel(current.structural_metrics.error_delta_mae)}/></div></Stage>}
          {revealed>=5&&<Connector key="c4"/>}{revealed>=5&&<Stage key="s5" index={5} title="The response is compared with 100 real-edge controls"><Comparison observed={current.structural_metrics.prediction_delta_abs} control={current.structural_metrics.control_mean_prediction_delta_abs}/><div className="mt-4 grid gap-3 sm:grid-cols-4"><Mini label="Control percentile" value={`${current.structural_metrics.control_percentile.toFixed(0)}th`}/><Mini label="Empirical p" value={current.structural_metrics.empirical_p.toFixed(3)}/><Mini label="BH adjusted p" value={current.structural_metrics.bh_adjusted_p.toFixed(3)}/><Mini label="95% bootstrap CI" value={`[${fmt(current.structural_metrics.effect_difference_bootstrap_ci[0])}, ${fmt(current.structural_metrics.effect_difference_bootstrap_ci[1])}]`}/></div></Stage>}
          {revealed>=6&&<Connector key="c5"/>}{revealed>=6&&<Stage key="s6" index={6} title="Three-dimensional diagnostic summary"><DiagnosticSummary record={current}/><div className="mt-4 flex items-center justify-between gap-4 text-[11px] text-ink-400"><span className="font-mono">{current.conclusion_id}</span><span className="rounded-lg border border-dashed px-3 py-2"><CircleDashed className="mr-1 inline" size={13}/>Cross-run: missing / null</span></div></Stage>}
        </AnimatePresence></div></div>
      </div>}
      <div className="flex items-start gap-2 rounded-lg border border-[#d6e3ec] bg-white px-4 py-3 text-[11.5px] text-ink-500"><CheckCircle2 size={15} className="shrink-0 text-accent"/>{catalog.notice}</div>
    </div>}
  </Section>
}

function UnexposedCase({record}:{record:CaseRecord}){return <div className="card border-amber-200 bg-amber-50 p-6"><div className="text-[10px] font-semibold uppercase tracking-[.12em] text-amber-700">Not exposed</div><h3 className="mt-2 font-serif text-2xl font-semibold text-[#263b59]">This graph window was not used by test {record.sample_index}</h3><p className="mt-3 max-w-3xl text-[12px] leading-relaxed text-ink-500">The selected input contains no time step assigned to window {record.window}. The edge-removal operation therefore never entered this sample's computation path, so stages 1–6 and their zero-valued response or control statistics are not shown.</p><p className="mt-2 text-[11px] text-ink-400">Active windows for this test: {(record.active_windows??[]).join(', ')||'none'}.</p></div>}

function ForecastChart({record,variableIndex}:{record:CaseRecord;variableIndex:number}){const base=record.baseline_prediction.map(r=>r[variableIndex]),removed=record.intervention_prediction.map(r=>r[variableIndex]),delta=removed.map((v,i)=>v-base[i]);return <div className="space-y-4"><LineChart series={[['Baseline prediction',base,'#16827f'],['Edge-removed prediction',removed,'#d65b52']]}/><DeltaChart values={delta}/><div className="grid gap-2 sm:grid-cols-3"><Mini label="Maximum upward delta" value={signed(Math.max(...delta))}/><Mini label="Maximum downward delta" value={signed(Math.min(...delta))}/><Mini label="Mean absolute delta" value={fmt(delta.reduce((sum,value)=>sum+Math.abs(value),0)/delta.length)}/></div></div>}
function ErrorChart({record,variableIndex}:{record:CaseRecord;variableIndex:number}){const truth=record.ground_truth.map(r=>r[variableIndex]);const base=record.baseline_prediction.map((r,i)=>Math.abs(r[variableIndex]-truth[i]));const removed=record.intervention_prediction.map((r,i)=>Math.abs(r[variableIndex]-truth[i]));return <LineChart series={[['Baseline absolute error',base,'#16827f'],['Edge-removed absolute error',removed,'#d65b52'],['Error Δ',removed.map((v,i)=>v-base[i]),'#7656a5']]}/>}
function LineChart({series}:{series:[string,number[],string][]}){const values=series.flatMap(([,data])=>data).filter(Number.isFinite),min=Math.min(...values),max=Math.max(...values),span=Math.max(max-min,1e-9);const path=(data:number[])=>data.map((value,index)=>`${index?'L':'M'} ${(index/95*920+55).toFixed(2)} ${(245-(value-min)/span*205).toFixed(2)}`).join(' ');return <div><div className="mb-2 flex flex-wrap justify-center gap-4">{series.map(([name,,color])=><span key={name} className="flex items-center gap-1.5 text-[10.5px] text-ink-500"><i className="h-0.5 w-5" style={{backgroundColor:color}}/>{name}</span>)}</div><div className="overflow-x-auto rounded-lg border border-line bg-white"><svg viewBox="0 0 1000 290" className="min-w-[650px]" role="img" aria-label="Stored 96-step trajectory"><line x1="55" y1="40" x2="55" y2="245" stroke="#cbd5df"/><line x1="55" y1="245" x2="975" y2="245" stroke="#cbd5df"/>{[1,24,48,72,96].map(step=><g key={step}><line x1={55+(step-1)/95*920} y1="245" x2={55+(step-1)/95*920} y2="250" stroke="#9aa8b7"/><text x={55+(step-1)/95*920} y="268" textAnchor="middle" fontSize="10" fill="#718096">{step}</text></g>)}<text x="10" y="44" fontSize="10" fill="#718096">{max.toFixed(3)}</text><text x="10" y="245" fontSize="10" fill="#718096">{min.toFixed(3)}</text>{series.map(([name,data,color])=><path key={name} d={path(data)} fill="none" stroke={color} strokeWidth="2.2" strokeLinejoin="round" vectorEffect="non-scaling-stroke"><title>{name}</title></path>)}</svg></div><div className="mt-1 text-center text-[10px] text-ink-400">Forecast step · exact values remain available in the audited catalog</div></div>}
function DiagnosticLocalization({record}:{record:CaseRecord}){const rows=record.diagnostic_localization.variable_ranking.slice(0,4),main=record.diagnostic_localization.response_intervals[0];return <div className="mt-5 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div><div className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-ink-400">Most affected outputs</div><div className="overflow-x-auto"><table className="w-full text-left text-[11px]"><thead className="text-ink-400"><tr><th className="p-2">Variable</th><th>Mean prediction Δ</th><th>Peak</th><th>Mean MAE Δ</th></tr></thead><tbody>{rows.map(r=><tr key={r.variable} className="border-t border-line"><td className="p-2 font-semibold">{r.variable}</td><td>{fmt(r.mean_absolute_prediction_delta)}</td><td>{fmt(r.max_absolute_prediction_delta)} · step {r.peak_step}</td><td>{signed(r.mean_absolute_error_delta)}</td></tr>)}</tbody></table></div></div><div className="rounded-xl bg-[#f5f7fa] p-4"><div className="text-[10px] uppercase tracking-wider text-ink-400">Primary response interval</div>{main?<><div className="mt-2 text-lg font-semibold text-ink-700">Step {main.start_step}–{main.end_step}</div><div className="mt-2 text-[11px] leading-relaxed text-ink-500">Peak at step {main.peak_step}; {pct(main.share_of_total_impact)} of total measured response.</div></>:<div className="mt-2 text-[12px] text-ink-500">No positive response interval detected.</div>}<div className="mt-3 text-[9.5px] leading-relaxed text-ink-400">Rule: {record.diagnostic_localization.response_interval_rule}.</div></div></div>}
function DiagnosticSummary({record}:{record:CaseRecord}){const m=record.structural_metrics,top=record.diagnostic_localization.variable_ranking[0],interval=record.diagnostic_localization.response_intervals[0];const response=m.prediction_delta_abs>0?'Measurable response':'No measurable response';const special=m.bh_adjusted_p<.05?'Control-distinguished response':'Not distinguished from controls';return <div className="grid gap-3 md:grid-cols-3"><DiagnosticCard label="Output response" status={response} text={top?`${top.variable} has the largest mean response${interval?`; primary interval step ${interval.start_step}–${interval.end_step}`:''}.`:'No localized output response.'}/><DiagnosticCard label="Performance consequence" status={performanceLabel(m.error_delta_mae)} text={`Overall MAE Δ ${signed(m.error_delta_mae)}.`}/><DiagnosticCard label="Relative specialness" status={special} text={`Control percentile ${m.control_percentile.toFixed(0)}th; BH-adjusted p ${m.bh_adjusted_p.toFixed(3)}.`}/></div>}
function DiagnosticCard({label,status,text}:{label:string;status:string;text:string}){return <div className="rounded-xl border border-line bg-[#fafbfd] p-4"><div className="text-[9.5px] uppercase tracking-wider text-ink-400">{label}</div><div className="mt-2 text-[13px] font-semibold text-ink-700">{status}</div><p className="mt-2 text-[11px] leading-relaxed text-ink-500">{text}</p></div>}
function Stage({index,title,children}:{index:number;title:string;children:ReactNode}){return <motion.article initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.65}} className="card overflow-hidden"><div className="border-b border-line bg-[#fafbfd] px-5 py-3"><span className="data-num mr-2 text-[10px] text-accent">0{index}</span><span className="text-[13px] font-semibold text-ink-700">{title}</span></div><div className="p-5">{children}</div></motion.article>}
function Connector(){return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="flex h-5 items-center justify-center text-[#9aabbc]"><ArrowDown size={16}/></motion.div>}
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <label><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-[.1em] text-ink-400">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-[#cad4df] bg-white px-3 py-2.5 text-[13px] font-semibold text-ink-700">{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
function Tag({text}:{text:string}){return <span className="h-fit rounded-full border border-[#cde2df] bg-[#eff8f6] px-2.5 py-1 text-[10.5px] font-semibold text-[#176e69]">{text}</span>}
function Mini({label,value,note}:{label:string;value:string;note?:string}){return <div className="rounded-lg bg-[#f5f7fa] p-3"><div className="text-[9.5px] uppercase tracking-[.08em] text-ink-400">{label}</div><div className="data-num mt-1 break-words text-[13px] font-semibold text-ink-800">{value}</div>{note&&<div className="mt-1 text-[10px] text-ink-400">{note}</div>}</div>}
function Comparison({observed,control}:{observed:number;control:number}){const max=Math.max(observed,control,1e-12);return <div className="space-y-3"><Bar label="Selected candidate" value={observed} max={max} color="bg-[#d65b52]"/><Bar label="Matched-control mean" value={control} max={max} color="bg-[#16827f]"/></div>}
function Bar({label,value,max,color}:{label:string;value:number;max:number;color:string}){return <div><div className="mb-1 flex justify-between text-[11px]"><span>{label}</span><span>{fmt(value)}</span></div><div className="h-2.5 rounded-full bg-[#e7ecf1]"><motion.div initial={{width:0}} animate={{width:`${Math.max(2,value/max*100)}%`}} className={`h-full rounded-full ${color}`}/></div></div>}
function DeltaChart({values}:{values:number[]}){const limit=Math.max(...values.map(Math.abs),1e-9),y=(value:number)=>140-value/limit*95,path=values.map((value,index)=>`${index?'L':'M'} ${(index/95*920+55).toFixed(2)} ${y(value).toFixed(2)}`).join(' ');return <div><div className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-ink-400">Signed prediction delta · independent zoomed scale</div><div className="overflow-x-auto rounded-lg border border-line bg-white"><svg viewBox="0 0 1000 280" className="min-w-[650px]"><line x1="55" y1="140" x2="975" y2="140" stroke="#95a3b2" strokeDasharray="5 5"/><path d={path} fill="none" stroke="#7656a5" strokeWidth="2.3"/><text x="8" y="48" fontSize="10" fill="#718096">+{limit.toFixed(6)}</text><text x="8" y="238" fontSize="10" fill="#718096">-{limit.toFixed(6)}</text></svg></div><div className="mt-1 text-center text-[10px] text-ink-400">Edge-removed prediction minus baseline prediction</div></div>}
function performanceLabel(v:number){return v>0?'Error increased':v<0?'Error decreased':'No measured MAE change'}
function fmt(v:number){return v.toFixed(6)} function signed(v:number){return `${v>=0?'+':''}${v.toFixed(6)}`} function pct(v:number){return `${(v*100).toFixed(1)}%`}
