import { useEffect, useState, type ReactNode } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowDown, CheckCircle2, CircleDashed, Pause, Play, RotateCcw, ShieldCheck } from 'lucide-react';
import { Section } from './layout/Section';

interface EdgeOption { edge_id:string; source:number; target:number; source_name:string; target_name:string; windows:number[]; topk_score:number; normalized_weight:number; retained_edge_rank:number }
interface Metrics { baseline_mae:number; intervention_mae:number; prediction_delta_abs:number; prediction_delta_rel:number; error_delta_mae:number; error_delta_mse:number; control_mean_prediction_delta_abs:number; control_percentile:number; empirical_p:number; bh_adjusted_p:number; standardized_effect_size:number|null; effect_difference_bootstrap_ci:[number,number]; weight_impact_spearman_rho:number; weight_impact_spearman_p:number; overlap_at_k:number }
interface CaseRecord { conclusion_id:string; sample_index:number; window:number; edge:EdgeOption; schedule:{state:string;current_epoch_equivalent:number;static_weight:number;learned_weight:number}; structural_metrics:Metrics; structural_metric_status:{standardized_effect_size:{status:string;reason:string|null}}; channel_mask_metrics:Metrics; step_impact:number[]; step_error_delta:number[]; variable_impact:number[]; controls:{repetitions:number;random_seed:number}; limitations:string[] }
interface Catalog { status:string;dataset:string;claim_label:string;samples:number[];variables:string[];edges:EdgeOption[];cases:CaseRecord[];notice:string;cross_run:{status:string;metrics:null;reason:string};source_runs:{intervention:string;evidence:string} }

const DATA_URL=`${import.meta.env.BASE_URL}data/evidence/etth1_intervention_catalog.json`;
const STAGES=['Candidate selected','Structural intervention','Prediction response','Error response','Matched controls','Evidence verdict'];

export function InterventionJourney(){
  const [catalog,setCatalog]=useState<Catalog|null>(null); const [error,setError]=useState(false);
  const [sample,setSample]=useState(0); const [edgeId,setEdgeId]=useState(''); const [windowId,setWindowId]=useState(0);
  const [revealed,setRevealed]=useState(1); const [playing,setPlaying]=useState(true);
  useEffect(()=>{fetch(DATA_URL).then(r=>{if(!r.ok)throw new Error();return r.json()}).then((data:Catalog)=>{setCatalog(data);setSample(data.samples[0]);setEdgeId(data.edges[0].edge_id);setWindowId(data.edges[0].windows[0])}).catch(()=>setError(true))},[]);
  const edge=catalog?.edges.find(item=>item.edge_id===edgeId);
  const current=catalog?.cases.find(item=>item.sample_index===sample&&item.window===windowId&&`${item.edge.source}->${item.edge.target}`===edgeId);
  useEffect(()=>{setRevealed(1);setPlaying(true)},[sample,edgeId,windowId]);
  useEffect(()=>{if(!playing||revealed>=STAGES.length)return;const timer=window.setTimeout(()=>setRevealed(value=>value+1),1050);return()=>window.clearTimeout(timer)},[playing,revealed]);
  useEffect(()=>{if(revealed>=STAGES.length)setPlaying(false)},[revealed]);
  const chooseEdge=(value:string)=>{setEdgeId(value);const next=catalog?.edges.find(item=>item.edge_id===value);if(next)setWindowId(next.windows[0])};
  return <Section id="intervention-lab" eyebrow="Precomputed intervention lab · ETTh1" title="Watch a candidate-edge removal unfold" intro="Choose an audited sample, candidate edge and real retained window. The page then reveals the stored checkpoint response step by step; no value is generated in the browser." className="bg-[#f5f8fb]">
    {error&&<div className="card border-red-200 p-5 text-sm text-red-700">Audited intervention catalog unavailable. No substitute result was generated.</div>}
    {!catalog&&!error&&<div className="card p-5 text-sm text-ink-400">Loading the audited ETTh1 catalog…</div>}
    {catalog&&current&&edge&&<div className="space-y-5">
      <div className="card grid gap-4 p-5 md:grid-cols-3">
        <Choice label="Test sample" value={String(sample)} onChange={value=>setSample(Number(value))} options={catalog.samples.map(value=>({value:String(value),label:`ETTh1 · test ${value}`}))}/>
        <Choice label="Candidate edge" value={edgeId} onChange={chooseEdge} options={catalog.edges.map(value=>({value:value.edge_id,label:`${value.source_name} → ${value.target_name}`}))}/>
        <Choice label="Retained graph window" value={String(windowId)} onChange={value=>setWindowId(Number(value))} options={edge.windows.map(value=>({value:String(value),label:`Window ${value}`}))}/>
        <div className="md:col-span-3 flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4">
          <div className="flex flex-wrap gap-2"><Tag text="Real ETTh1 checkpoint"/><Tag text="Final schedule · 0.1 static + 0.9 learned"/><Tag text="Stored evidence only"/></div>
          <div className="flex gap-2"><button className="journey-button" onClick={()=>setPlaying(value=>!value)}>{playing?<Pause size={13}/>:<Play size={13}/>} {playing?'Pause':'Continue'}</button><button className="journey-button" onClick={()=>{setRevealed(1);setPlaying(true)}}><RotateCcw size={13}/>Replay</button></div>
        </div>
      </div>
      <div className="grid gap-4 lg:grid-cols-[210px_1fr]">
        <ol className="card h-fit p-3">{STAGES.map((stage,index)=><li key={stage} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-[12px] transition ${index<revealed?'bg-[#edf6f5] font-semibold text-[#176e69]':'text-ink-300'}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full text-[10px] ${index<revealed?'bg-[#16827f] text-white':'bg-[#edf0f3]'}`}>{index+1}</span>{stage}</li>)}</ol>
        <div className="space-y-3"><AnimatePresence initial={false}>
          {revealed>=1&&<Stage key="candidate" index={1} title="A structural candidate is selected" delay={0}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="font-serif text-[27px] font-semibold text-[#263b59]">{edge.source_name} <span className="text-accent">→</span> {edge.target_name}</div><p className="mt-2 text-[12.5px] text-ink-500">Sample {sample} · window {windowId} · retained-edge rank {current.edge.retained_edge_rank} · Top-K score {fmt(current.edge.topk_score)}</p></div><span className="rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-[11px] font-semibold text-amber-800">Candidate Pattern</span></div></Stage>}
          {revealed>=2&&<Connector key="c1"/>}{revealed>=2&&<Stage key="intervention" index={2} title="The edge is removed inside the real message-passing graph" delay={0.05}><div className="grid gap-3 sm:grid-cols-3"><Mini label="Before" value={fmt(current.edge.normalized_weight)} note="normalized channel weight"/><Mini label="After" value="0.000000" note="selected structural edge"/><Mini label="Protocol" value="Renormalized" note="remaining row weights recomputed"/></div><p className="mt-4 text-[12px] leading-relaxed text-ink-500">The checkpoint parameters stay frozen. Only {edge.source_name}→{edge.target_name} in window {windowId} is removed, then the affected row is normalized and the stored real forward is retrieved.</p></Stage>}
          {revealed>=3&&<Connector key="c2"/>}{revealed>=3&&<Stage key="prediction" index={3} title="The prediction response unfolds across 96 forecast steps" delay={0.05}><StepImpact values={current.step_impact}/><div className="mt-4 grid gap-3 sm:grid-cols-3"><Mini label="Mean absolute prediction Δ" value={fmt(current.structural_metrics.prediction_delta_abs)} note="all steps × variables"/><Mini label="Relative prediction Δ" value={fmt(current.structural_metrics.prediction_delta_rel)} note="relative to mean |baseline|"/><Mini label="Largest step response" value={fmt(Math.max(...current.step_impact))} note={`forecast step ${current.step_impact.indexOf(Math.max(...current.step_impact))+1}`}/></div></Stage>}
          {revealed>=4&&<Connector key="c3"/>}{revealed>=4&&<Stage key="error" index={4} title="Prediction change is separated from error change" delay={0.05}><ErrorRibbon values={current.step_error_delta}/><div className="mt-4 grid gap-3 sm:grid-cols-3"><Mini label="Baseline MAE" value={fmt(current.structural_metrics.baseline_mae)}/><Mini label="Intervention MAE" value={fmt(current.structural_metrics.intervention_mae)}/><Mini label="MAE Δ" value={signed(current.structural_metrics.error_delta_mae)} note={current.structural_metrics.error_delta_mae>0?'error increased for this sample':current.structural_metrics.error_delta_mae<0?'error decreased for this sample':'no measured MAE change'}/></div></Stage>}
          {revealed>=5&&<Connector key="c4"/>}{revealed>=5&&<Stage key="controls" index={5} title="The response is compared with 100 real-edge controls" delay={0.05}><Comparison observed={current.structural_metrics.prediction_delta_abs} control={current.structural_metrics.control_mean_prediction_delta_abs}/><div className="mt-4 grid gap-3 sm:grid-cols-4"><Mini label="Control percentile" value={`${current.structural_metrics.control_percentile.toFixed(0)}th`}/><Mini label="Empirical p" value={current.structural_metrics.empirical_p.toFixed(3)}/><Mini label="BH adjusted p" value={current.structural_metrics.bh_adjusted_p.toFixed(3)}/><Mini label="95% bootstrap CI" value={`[${fmt(current.structural_metrics.effect_difference_bootstrap_ci[0])}, ${fmt(current.structural_metrics.effect_difference_bootstrap_ci[1])}]`}/></div></Stage>}
          {revealed>=6&&<Connector key="c5"/>}{revealed>=6&&<Stage key="verdict" index={6} title="The evidence is reported without upgrading the claim" delay={0.05}><div className="grid gap-4 md:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2 text-[13px] font-semibold text-ink-700"><ShieldCheck size={17} className="text-accent"/>Stored interventional model evidence</div><p className="mt-2 text-[13px] leading-relaxed text-ink-500">Removing this candidate produced a measured prediction change of {fmt(current.structural_metrics.prediction_delta_abs)}. Its BH-adjusted p value is {current.structural_metrics.bh_adjusted_p.toFixed(3)}. This record does not establish real-world causality or cross-training stability.</p>{current.structural_metrics.standardized_effect_size===null&&<p className="mt-2 rounded-lg bg-amber-50 p-3 text-[11.5px] text-amber-800">Standardized effect size: null — {current.structural_metric_status.standardized_effect_size.reason}</p>}</div><div className="rounded-xl border border-dashed border-[#b8c5d2] bg-[#f7f9fb] p-4 text-center"><CircleDashed className="mx-auto text-ink-400" size={20}/><div className="mt-2 text-[11px] font-semibold text-ink-600">Cross-run</div><div className="data-num mt-1 text-[11px] text-ink-400">missing / null</div></div></div><div className="mt-4 flex flex-wrap gap-2 text-[10.5px] text-ink-400"><span className="font-mono">{current.conclusion_id}</span><span>·</span><span>control seed {current.controls.random_seed}</span><span>·</span><span>{current.controls.repetitions} repetitions</span></div></Stage>}
        </AnimatePresence></div>
      </div>
      <div className="flex items-start gap-2 rounded-lg border border-[#d6e3ec] bg-white px-4 py-3 text-[11.5px] leading-relaxed text-ink-500"><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-accent"/>{catalog.notice}</div>
    </div>}
  </Section>
}

function Stage({index,title,children,delay}:{index:number;title:string;children:ReactNode;delay:number}){return <motion.article initial={{opacity:0,y:18,height:0}} animate={{opacity:1,y:0,height:'auto'}} transition={{duration:.65,delay,ease:[.22,1,.36,1]}} className="card overflow-hidden"><div className="border-b border-line bg-[#fafbfd] px-5 py-3"><span className="data-num mr-2 text-[10px] text-accent">0{index}</span><span className="text-[13px] font-semibold text-ink-700">{title}</span></div><div className="p-5">{children}</div></motion.article>}
function Connector(){return <motion.div initial={{opacity:0,scaleY:0}} animate={{opacity:1,scaleY:1}} transition={{duration:.45}} className="flex h-5 origin-top items-center justify-center text-[#9aabbc]"><ArrowDown size={16}/></motion.div>}
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <label><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-[.1em] text-ink-400">{label}</span><select value={value} onChange={event=>onChange(event.target.value)} className="w-full rounded-lg border border-[#cad4df] bg-white px-3 py-2.5 text-[13px] font-semibold text-ink-700 outline-none focus:border-accent focus:ring-2 focus:ring-[#16827f22]">{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>}
function Tag({text}:{text:string}){return <span className="rounded-full border border-[#cde2df] bg-[#eff8f6] px-2.5 py-1 text-[10.5px] font-semibold text-[#176e69]">{text}</span>}
function Mini({label,value,note}:{label:string;value:string;note?:string}){return <div className="rounded-lg bg-[#f5f7fa] p-3"><div className="text-[9.5px] uppercase tracking-[.08em] text-ink-400">{label}</div><div className="data-num mt-1 break-words text-[13px] font-semibold text-ink-800">{value}</div>{note&&<div className="mt-1 text-[10px] leading-snug text-ink-400">{note}</div>}</div>}
function StepImpact({values}:{values:number[]}){const max=Math.max(...values,1e-12);return <div><div className="mb-2 flex justify-between text-[10px] text-ink-400"><span>Forecast step 1</span><span>96</span></div><div className="flex h-24 items-end gap-[2px] rounded-lg border border-line bg-[#f8fafc] px-3 py-2">{values.map((value,index)=><motion.div key={index} initial={{height:0,opacity:0}} animate={{height:`${Math.max(2,value/max*100)}%`,opacity:1}} transition={{duration:.35,delay:index*.012}} title={`Step ${index+1}: ${value}`} className="min-w-0 flex-1 rounded-t-sm bg-gradient-to-t from-[#16827f] to-[#66b8b2]"/>)}</div></div>}
function ErrorRibbon({values}:{values:number[]}){const max=Math.max(...values.map(Math.abs),1e-12);return <div><div className="relative flex h-24 items-center gap-[2px] rounded-lg border border-line bg-[#f8fafc] px-3"><div className="absolute inset-x-3 top-1/2 border-t border-dashed border-[#aeb9c5]"/>{values.map((value,index)=><motion.div key={index} initial={{height:0}} animate={{height:`${Math.max(1,Math.abs(value)/max*46)}%`}} transition={{duration:.35,delay:index*.012}} title={`Step ${index+1}: ${value>=0?'+':''}${value}`} className={`relative min-w-0 flex-1 rounded-sm ${value>=0?'self-start mt-[46px] bg-[#d96a61]':'self-end mb-[46px] bg-[#5c91bf]'}`}/>)}</div><div className="mt-2 flex justify-between text-[10px] text-ink-400"><span className="text-[#5c91bf]">Below zero: error decreased</span><span className="text-[#b94d45]">Above zero: error increased</span></div></div>}
function Comparison({observed,control}:{observed:number;control:number}){const max=Math.max(observed,control,1e-12);return <div className="space-y-3"><Bar label="Selected candidate" value={observed} max={max} color="bg-[#d65b52]"/><Bar label="Matched-control mean" value={control} max={max} color="bg-[#16827f]"/></div>}
function Bar({label,value,max,color}:{label:string;value:number;max:number;color:string}){return <div><div className="mb-1 flex justify-between text-[11px]"><span className="text-ink-500">{label}</span><span className="data-num font-semibold">{fmt(value)}</span></div><div className="h-2.5 rounded-full bg-[#e7ecf1]"><motion.div initial={{width:0}} animate={{width:`${Math.max(2,value/max*100)}%`}} transition={{duration:.8,ease:'easeOut'}} className={`h-full rounded-full ${color}`}/></div></div>}
function fmt(value:number){return value.toFixed(6)} function signed(value:number){return `${value>=0?'+':''}${value.toFixed(6)}`}
