import { Section } from './layout/Section';

const ITEMS = [
  { h: 'Audited artifacts, not browser inference', b: 'The website loads outputs generated by the supplied checkpoint and real test split. Prediction, graph, attention, intervention, and control values are not synthesized in the frontend.' },
  { h: 'Model behavior, not causality', b: 'Graph-edge interventions measure changes inside this trained model. They do not identify causal relationships between variables in the real system.' },
  { h: 'One predeclared Phase 5 case', b: 'The current statistical evidence validates the Phase 4 candidate for one ETTh2 checkpoint, sample, and window. It must not be generalized to the complete dataset.' },
  { h: 'Cross-run stability not evaluated', b: 'Only one real checkpoint is available per dataset. Cross-training Jaccard, recurrence, weight stability, and intervention consistency remain null rather than being simulated.' },
];

export function Limitations(){return <Section id="limitations" eyebrow="Scope & limitations" title="What the current evidence supports" intro="The site separates measured results from missing evidence so the final conclusion stays proportional to the experiment."><div className="grid gap-4 md:grid-cols-2">{ITEMS.map((item)=><div key={item.h} className="card p-5"><h3 className="text-[15px] font-semibold">{item.h}</h3><p className="mt-1.5 text-[13.5px] leading-relaxed text-ink-500">{item.b}</p></div>)}</div></Section>}
