import { useEffect, useMemo, useState } from 'react';
import { Activity, Check, ChevronRight, Database, GitBranch, LoaderCircle, ShieldCheck } from 'lucide-react';
import { GraphNetwork } from './charts/GraphNetwork';
import { loadMsgnetCatalog, type MsgnetCatalog, type MsgnetEdgeImpact, type MsgnetSample } from '@/data/msgnetLoader';
import type { GraphEdge } from '@/types/demo';

function useMsgnet(){const [catalog,setCatalog]=useState<MsgnetCatalog|null>(null),[failure,setFailure]=useState('');useEffect(()=>{loadMsgnetCatalog().then(setCatalog).catch((e:Error)=>setFailure(e.message))},[]);return {catalog,failure}}
function LoadState({failure}:{failure:string}){return <div className={`flex min-h-[320px] items-center justify-center ${failure?'text-red-700':'text-ink-400'}`}>{failure||<><LoaderCircle className="mr-2 animate-spin" size={18}/>Loading audited MSGNet evidence…</>}</div>}
const edgeKey=(e:MsgnetEdgeImpact)=>`${e.scale_index}-${e.source}-${e.target}`;

export function MsgnetDataWorkspace(){
  const {catalog,failure}=useMsgnet(),[sampleId,setSampleId]=useState(0),[variable,setVariable]=useState(6),[view,setView]=useState<'forecast'|'graph'>('forecast'),[scale,setScale]=useState(0),[layout,setLayout]=useState<'heatmap'|'network'|'3d'>('heatmap'),[selected,setSelected]=useState<{source:number;target:number}|null>(null);
  if(!catalog)return <LoadState failure={failure}/>;const sample=catalog.samples[String(sampleId)],context=sample.contexts[scale],edges=matrixEdges(context.adaptive);
  return <div className="border-b border-line bg-white"><div className="mx-auto grid max-w-[1400px] gap-6 px-5 py-14 lg:grid-cols-[280px_1fr_320px]">
    <aside className="space-y-5"><Control label="Dataset" value="ETTh1" disabled options={['ETTh1']} onChange={()=>{}}/><Control label="Test sample" value={String(sampleId)} options={Object.keys(catalog.samples)} onChange={v=>{setSampleId(Number(v));setSelected(null)}}/><Control label="Target variable" value={String(variable)} options={catalog.variables.map((v,i)=>`${i}|${v}`)} labels onChange={v=>setVariable(Number(v.split('|')[0]))}/><Group label="View"><Tabs value={view} items={[['forecast','Forecast'],['graph','Dynamic graph']]} onChange={v=>setView(v as typeof view)}/></Group>{view==='graph'&&<><Group label="Scale context"><div className="grid gap-2">{sample.contexts.map((c,i)=><button key={i} onClick={()=>{setScale(i);setSelected(null)}} className={pick(scale===i)}><b>Scale {i+1} · period {c.period}</b><small>FFT {c.fft_strength.toFixed(3)} · contribution {(c.scale_contribution*100).toFixed(1)}%</small></button>)}</div></Group><Group label="Layout"><Tabs value={layout} items={[['heatmap','Heatmap'],['network','Network'],['3d','3D']]} onChange={v=>setLayout(v as typeof layout)}/></Group></>}</aside>
    <main className="card min-h-[540px] p-5"><div className="flex items-baseline justify-between"><h3 className="text-[15px] font-semibold">{view==='forecast'?`Forecast · ${catalog.variables[variable]} (ETTh1)`:`Scale dynamic graph · context ${scale+1}/${sample.contexts.length}`}</h3><span className="font-mono text-[11px] text-ink-400">test {sampleId} · h96</span></div>{view==='forecast'?<><ForecastSvg history={sample.history[variable]} truth={sample.ground_truth[variable]} prediction={sample.prediction[variable]}/><div className="mt-4 flex gap-5 text-[10px] text-ink-400"><Legend color="#8491a5" label="History"/><Legend color="#16827f" label="Ground truth"/><Legend color="#d6453b" label="Prediction" dashed/></div></>:layout==='heatmap'?<Matrix matrix={context.adaptive} variables={catalog.variables} selected={selected} onPick={(source,target)=>setSelected({source,target})}/>:layout==='network'?<div className="flex justify-center pt-8"><GraphNetwork variables={catalog.variables} edges={edges} layout="circular" showLabels threshold={0} target={variable} highlightTarget selectedNode={null} selectedEdge={selected} onClickEdge={e=>setSelected({source:e.source,target:e.target})} size={440}/></div>:<ScaleGraph3D sample={sample} variables={catalog.variables} activeScale={scale} selected={selected} onScale={setScale} onEdge={setSelected}/>}</main>
    <aside className="card h-fit overflow-hidden"><header className="bg-[#263b59] px-5 py-4 text-white"><div className="text-[9px] uppercase tracking-wider text-white/60">Explanation inspector</div><h3 className="mt-1 font-serif text-xl font-semibold">MSGNet real artifact</h3></header><div className="space-y-4 p-5"><Mini label="Checkpoint" value={catalog.checkpoint_sha256.slice(0,16)+'…'}/><Mini label="Forecast MSE / MAE" value={`${sample.metrics.mse.toFixed(4)} / ${sample.metrics.mae.toFixed(4)}`}/><Mini label="Current scale" value={`period ${context.period} · ${(context.scale_contribution*100).toFixed(1)}% contribution`}/>{selected?<><Mini label="Selected edge" value={`${catalog.variables[selected.source]} → ${catalog.variables[selected.target]}`}/><Mini label="Graph weight" value={context.adaptive[selected.source][selected.target].toFixed(4)}/></>:<p className="rounded-lg bg-[#f3f6f8] p-3 text-[10px] text-ink-400">Select a graph edge or heatmap cell to inspect its real stored weight.</p>}<p className="text-[10px] leading-relaxed text-ink-400">The browser reads checkpoint-derived matrices and predictions. Graph weights describe model associations, not real-world causality.</p></div></aside>
  </div></div>
}

export function MsgnetDiagnosticWorkspace(){
 const {catalog,failure}=useMsgnet(),[sampleId,setSampleId]=useState(0),[scale,setScale]=useState(0),[selectedKey,setSelectedKey]=useState('');if(!catalog)return <LoadState failure={failure}/>;const sample=catalog.samples[String(sampleId)],edges=sample.edge_impacts.filter(e=>e.scale_index===scale).sort((a,b)=>b.adaptive_weight-a.adaptive_weight),selected=edges.find(e=>edgeKey(e)===selectedKey)||edges[0],supported=sample.edge_impacts.filter(e=>e.statistics.bh_adjusted_p<.05).length;
 return <div className="border-y border-line bg-[#f4f7fa]"><nav className="border-b border-line bg-white px-5 py-3"><div className="mx-auto flex max-w-[1240px] items-center justify-between"><div><div className="text-[10px] font-semibold uppercase tracking-[.16em] text-accent">DGraInsight · audited diagnostic workspace</div><div className="text-[11px] text-ink-400">Load stored evidence → select an edge → inspect change → review evidence → bounded conclusion</div></div><span className="rounded-lg bg-[#edf6f5] px-3 py-2 text-[10px] font-semibold text-[#176e69]">MSGNet · scale-edge removal</span></div></nav><main className="mx-auto max-w-[1240px] space-y-6 px-5 py-10">
 <Workflow/><section className="grid gap-5 lg:grid-cols-[1fr_330px]"><div className="space-y-5"><section className="card overflow-hidden"><header className="border-b border-line bg-[#fafbfd] px-5 py-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-accent">01 · audited precomputed package</div><h2 className="mt-1 font-serif text-2xl font-semibold text-[#263b59]">ETTh1 MSGNet evidence is loaded</h2></header><div className="grid gap-3 p-5 sm:grid-cols-4"><Mini label="Audited tests" value={String(Object.keys(catalog.samples).length)}/><Mini label="Scale contexts" value="3 per test"/><Mini label="Stored edge cases" value={String(catalog.case_count)}/><Mini label="BH-supported cases" value={String(Object.values(catalog.samples).flatMap(s=>s.edge_impacts).filter(e=>e.statistics.bh_adjusted_p<.05).length)}/></div></section><section className="card p-5"><div className="text-[10px] font-semibold uppercase tracking-wider text-accent">02 · select a real scale edge</div><div className="mt-4 grid gap-3 sm:grid-cols-2">{edges.slice(0,12).map(e=><button key={edgeKey(e)} onClick={()=>setSelectedKey(edgeKey(e))} className={`rounded-xl border p-4 text-left ${e===selected?'border-[#16827f] bg-[#edf7f6]':'border-line bg-white'}`}><div className="font-serif text-lg font-semibold text-[#263b59]">{e.source_name} <span className="text-[#16827f]">→</span> {e.target_name}</div><div className="mt-3 h-1.5 rounded-full bg-[#dfe7eb]"><div className="h-full rounded-full bg-[#36a39e]" style={{width:`${Math.min(100,e.adaptive_weight*100)}%`}}/></div><div className="mt-2 text-[10px] text-ink-400">weight {e.adaptive_weight.toFixed(4)} · scale {scale+1}</div></button>)}</div></section></div><aside className="card h-fit overflow-hidden lg:sticky lg:top-5"><header className="bg-[#263b59] px-5 py-4 text-white"><div className="text-[9px] uppercase tracking-wider text-white/60">Live evidence rail</div><h3 className="mt-1 font-serif text-xl font-semibold">{selected.source_name} → {selected.target_name}</h3></header><div className="space-y-4 p-5"><Mini label="Current test" value={`ETTh1 · test ${sampleId}`}/><Mini label="Scale / period" value={`${scale+1} / ${sample.contexts[scale].period}`}/><Mini label="Graph weight" value={selected.adaptive_weight.toFixed(4)}/><Mini label="Prediction Δ" value={selected.prediction_delta_abs.toFixed(6)}/><Mini label="MAE Δ" value={signed(selected.error_delta_mae)}/><Mini label="BH adjusted p" value={selected.statistics.bh_adjusted_p.toFixed(3)}/></div></aside></section>
 <section className="card p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-[10px] font-semibold uppercase tracking-wider text-accent">03 · choose scale and test period</div><h3 className="mt-1 font-serif text-xl font-semibold text-[#263b59]">Real intervention navigator</h3></div><div className="flex gap-2">{sample.contexts.map((c,i)=><button key={i} onClick={()=>{setScale(i);setSelectedKey('')}} className={`rounded-lg px-3 py-2 text-[10px] font-semibold ${i===scale?'bg-[#263b59] text-white':'bg-[#edf1f5] text-ink-600'}`}>Scale {i+1} · p{c.period}</button>)}</div></div><div className="mt-5 flex gap-2">{Object.keys(catalog.samples).map(id=><button key={id} onClick={()=>{setSampleId(Number(id));setSelectedKey('')}} className={`h-9 min-w-12 rounded-md border text-[10px] font-semibold ${Number(id)===sampleId?'border-[#263b59] bg-[#263b59] text-white':'border-line bg-white'}`}>test {id}</button>)}</div></section>
 <section className="card overflow-hidden"><header className="border-b border-line bg-[#fafbfd] px-5 py-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-accent">04 · inspect stored intervention</div><h3 className="mt-1 font-serif text-2xl font-semibold text-[#263b59]">{selected.source_name} → {selected.target_name} · test {sampleId}</h3></header><div className="grid gap-3 p-5 sm:grid-cols-4"><Mini label="Prediction Δ" value={selected.prediction_delta_abs.toFixed(6)}/><Mini label="MAE Δ" value={signed(selected.error_delta_mae)}/><Mini label="Matched-control mean" value={selected.statistics.control_mean_prediction_delta_abs.toFixed(6)}/><Mini label="Empirical / BH p" value={`${selected.statistics.empirical_p.toFixed(3)} / ${selected.statistics.bh_adjusted_p.toFixed(3)}`}/></div><div className="border-t border-line bg-amber-50 px-5 py-4 text-[11px] text-amber-800">Intervention prediction trajectory: not exported in the audited package. No synthetic before/after curve is substituted.</div></section>
 <section className="card p-5"><div className="text-[10px] font-semibold uppercase tracking-wider text-accent">05 · bounded conclusion</div><h3 className="mt-1 font-serif text-xl font-semibold text-[#263b59]">Model-internal response, not causality</h3><p className="mt-3 text-[12px] leading-relaxed text-ink-500">Removing {selected.source_name} → {selected.target_name} at scale {scale+1} changed the stored prediction by {selected.prediction_delta_abs.toFixed(6)} and MAE by {signed(selected.error_delta_mae)}. {selected.statistics.bh_adjusted_p<.05?'This case passes the stored BH-adjusted threshold.':'This case does not pass the stored BH-adjusted threshold.'} The result is limited to this checkpoint, test sample and scale context.</p><p className="mt-3 text-[10px] text-ink-400">Current sample has {supported} BH-supported cases. Cross-checkpoint stability is not evaluated.</p></section>
 </main></div>
}

function Workflow(){const steps=[[Database,'Load evidence'],[GitBranch,'Select edge'],[Activity,'Inspect change'],[ShieldCheck,'Review evidence'],[Check,'Conclusion']] as const;return <section className="card p-4"><div className="flex overflow-x-auto">{steps.map(([Icon,label],i)=><div key={label} className="flex min-w-[180px] flex-1 items-center"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#176e69] text-white"><Icon size={15}/></span><span className="ml-2 text-[11px] font-semibold"><small className="block text-[9px] font-normal uppercase text-ink-400">Step {i+1}</small>{label}</span>{i<4&&<ChevronRight className="mx-3 text-ink-300" size={15}/>}</div>)}</div></section>}
function Group({label,children}:{label:string;children:React.ReactNode}){return <div><div className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-ink-400">{label}</div>{children}</div>}
function Control({label,value,options,onChange,disabled=false,labels=false}:{label:string;value:string;options:string[];onChange:(v:string)=>void;disabled?:boolean;labels?:boolean}){return <label className="block"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-wider text-ink-400">{label}</span><select disabled={disabled} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-line bg-white px-3 py-2 text-[12px]">{options.map(v=><option key={v} value={labels?v.split('|')[0]:v}>{labels?v.split('|')[1]:v}</option>)}</select></label>}
function Tabs({value,items,onChange}:{value:string;items:string[][];onChange:(v:string)=>void}){return <div className="flex rounded-lg bg-[#edf1f5] p-1">{items.map(([v,l])=><button key={v} onClick={()=>onChange(v)} className={`flex-1 rounded-md px-2 py-2 text-[10px] font-semibold ${value===v?'bg-white text-accent shadow-sm':'text-ink-500'}`}>{l}</button>)}</div>}
const pick=(active:boolean)=>`rounded-lg border px-3 py-3 text-left text-[11px] ${active?'border-[#16827f] bg-[#edf7f6]':'border-line bg-white'}`;
function Mini({label,value}:{label:string;value:string}){return <div><div className="text-[9px] uppercase tracking-wider text-ink-400">{label}</div><div className="mt-1 break-all font-mono text-[11px] font-semibold text-[#263b59]">{value}</div></div>}
const signed=(n:number)=>`${n>0?'+':''}${n.toFixed(6)}`;
function Legend({color,label,dashed=false}:{color:string;label:string;dashed?:boolean}){return <span className="flex items-center gap-2"><i className="w-5 border-t-2" style={{borderColor:color,borderStyle:dashed?'dashed':'solid'}}/>{label}</span>}
function ForecastSvg({history,truth,prediction}:{history:number[];truth:number[];prediction:number[]}){const all=[...history,...truth,...prediction],min=Math.min(...all),max=Math.max(...all),range=max-min||1,w=760,h=390,p=22,pt=(v:number,i:number,n:number,x0:number,x1:number)=>`${x0+i/Math.max(1,n-1)*(x1-x0)},${h-p-(v-min)/range*(h-p*2)}`,split=w*.5;return <svg viewBox={`0 0 ${w} ${h}`} className="mt-7 h-[390px] w-full"><rect x={split} width={w-split} height={h} fill="#f5f8f8"/><line x1={split} x2={split} y2={h} stroke="#ccd7dc" strokeDasharray="4 5"/><polyline fill="none" stroke="#8491a5" strokeWidth="2" points={history.map((v,i)=>pt(v,i,history.length,p,split-10)).join(' ')}/><polyline fill="none" stroke="#16827f" strokeWidth="2.2" points={truth.map((v,i)=>pt(v,i,truth.length,split+10,w-p)).join(' ')}/><polyline fill="none" stroke="#d6453b" strokeWidth="2" strokeDasharray="5 4" points={prediction.map((v,i)=>pt(v,i,prediction.length,split+10,w-p)).join(' ')}/></svg>}
function Matrix({matrix,variables,selected,onPick}:{matrix:number[][];variables:string[];selected:{source:number;target:number}|null;onPick:(s:number,t:number)=>void}){const max=Math.max(...matrix.flat(),.001);return <div className="mx-auto mt-8 grid max-w-[560px] gap-1" style={{gridTemplateColumns:`58px repeat(${variables.length},1fr)`}}><span/>{variables.map(v=><span className="text-center text-[9px] text-ink-400" key={v}>{v}</span>)}{matrix.map((row,s)=><div className="contents" key={s}><span className="flex items-center text-[9px] text-ink-400">{variables[s]}</span>{row.map((v,t)=><button key={t} disabled={s===t} onClick={()=>onPick(s,t)} title={`${variables[s]} → ${variables[t]}: ${v.toFixed(4)}`} className={`aspect-square rounded border ${selected?.source===s&&selected.target===t?'border-red-500 ring-2 ring-red-200':'border-white'}`} style={{background:s===t?'#e8edf0':`rgba(22,130,127,${.08+.82*v/max})`}}/>)}</div>)}</div>}
function matrixEdges(matrix:number[][]):GraphEdge[]{return matrix.flatMap((r,s)=>r.map((weight,t)=>({source:s,target:t,weight,rank:0,kept:s!==t&&weight>0}))).filter(e=>e.source!==e.target).sort((a,b)=>b.weight-a.weight).map((e,i)=>({...e,rank:i+1}))}
function ScaleGraph3D({sample,variables,activeScale,selected,onScale,onEdge}:{sample:MsgnetSample;variables:string[];activeScale:number;selected:{source:number;target:number}|null;onScale:(n:number)=>void;onEdge:(e:{source:number;target:number})=>void}){return <div className="mt-6 overflow-x-auto bg-gradient-to-b from-[#f5f8fb] to-[#e8eef4] px-8 py-10 [perspective:900px]"><div className="flex min-w-[780px] justify-center gap-8 [transform:rotateX(54deg)_rotateZ(-18deg)] [transform-style:preserve-3d]">{sample.contexts.map((c,i)=><button key={i} onClick={()=>onScale(i)} className={`relative h-[330px] w-[260px] shrink-0 rounded-xl border bg-white/90 p-3 text-left shadow-xl transition ${i===activeScale?'border-[#16827f] ring-4 ring-[#16827f]/20':'border-line opacity-75'}`}><div className="absolute -top-7 left-2 font-mono text-[11px] font-semibold text-[#263b59]">Scale {i+1} · period {c.period}</div><GraphNetwork variables={variables} edges={matrixEdges(c.adaptive)} layout="circular" showLabels={false} threshold={0} target={-1} highlightTarget={false} selectedNode={null} selectedEdge={i===activeScale?selected:null} onClickEdge={e=>{onScale(i);onEdge({source:e.source,target:e.target})}} size={235}/></button>)}</div><p className="mt-8 text-center text-[10px] text-ink-400">Three checkpoint-derived scale graphs arranged in depth; no coordinates or weights are synthesized.</p></div>}
